name: 'Run Firefox preformance tests'
description: 'Run Firefox preformance tests using JetStream 2.2'
inputs:
  firefox-exec:
    description: 'The Firefox command to run (e.g. "firefox" or a path to an executable)'
    required: true
    type: string
  results-file:
    description: 'The file name under which to save results'
    required: true
    type: string
  
runs:
  using: "composite"
  steps:
  - name: Get JetStream2.2
    shell: bash
    run: |
        git clone https://github.com/WebKit/JetStream.git
        cd JetStream
        git checkout JetStream2.2
  
  - name: Write server script
    shell: bash
    run: |
        cat <<EOF > ${{ github.workspace }}/JetStream/server.py
        #!/usr/bin/env python3
        from http.server import HTTPServer, SimpleHTTPRequestHandler
        import json

        class CustomHandler(SimpleHTTPRequestHandler):
            def do_POST(self):
                if self.path == '/report':
                    content_length = int(self.headers.get('Content-Length', 0))
                    body = self.rfile.read(content_length)
                    with open("${{ inputs.results-file }}", 'w', encoding='utf-8') as f:
                        json.dump(json.loads(body.decode('utf-8')), f)
                    self.send_response(200)
                else:
                    super().do_POST()

        if __name__ == '__main__':
            httpd = HTTPServer(('localhost', 8000), CustomHandler)
            httpd.serve_forever()
        EOF
        chmod +x ${{ github.workspace }}/JetStream/server.py

  - name: Write kill script
    shell: bash
    run: |
        cat <<EOF > ${{ github.workspace }}/JetStream/kill.sh
        #!/bin/bash
        while true; do
          if [ -f "${{ inputs.results-file }}" ]; then
            break
          fi
          sleep 5
        done
        ps aux | grep -i xvfb | head -1 | tr -s ' ' | cut -d ' ' -f 2 | xargs -I {} kill {}
        kill "\$(pgrep -f 'python3 ./server.py')"
        kill "\$(pgrep firefox)"
        EOF
        chmod +x ${{ github.workspace }}/JetStream/kill.sh

  - name: Write consolidate script
    shell: bash
    run: |
        cat <<EOF > ${{ github.workspace }}/consolidate-jetstream-results.py
        #!/usr/bin/env python3
        import json
        import sys

        def update_max(json_1, json_2):
            tests_1 = json_1['JetStream2.0']['tests']
            tests_2 = json_2['JetStream2.0']['tests']
            for metric, data in tests_1.items():
                score_1 = data['metrics']['Score']['current'][0]
                score_2 = tests_2[metric]['metrics']['Score']['current'][0]
                data['metrics']['Score']['current'][0] = max(score_1, score_2)
            return json_1

        if len(sys.argv) != 3:
            print('should pass two input files', file=sys.stderr)
            exit(1)

        with open(sys.argv[1], 'r') as f:
            test_1 = json.load(f)
        with open(sys.argv[2], 'r') as f:
            test_2 = json.load(f)
        with open(sys.argv[1], 'w') as f:
            json.dump(update_max(test_1, test_2), f)
        EOF
        chmod +x ${{ github.workspace }}/consolidate-jetstream-results.py

  - name: Run firefox performance tests
    shell: bash
    run: |
        cd JetStream

        for i in $(seq 1 30); do

          ./server.py &
          server_pid=$!
          sudo ./kill.sh &
          kill_pid=$!

          echo "Make sure the server is up and running"
          for _ in $(seq 10); do
            if curl -I 'http://localhost:8000' -o /dev/null 2>/dev/null; then
              break
            fi
            sleep 1
          done

          echo "Running firefox performance tests: iteration $i"
          xvfb-run -s '-terminate' ${{ inputs.firefox-exec }} 'http://localhost:8000/?startDelay=1&report=true' || true

          if [ $i -eq 1 ]; then
            mv "${{ inputs.results-file }}" intermediate-results.json
          else
            mv "${{ inputs.results-file }}" "results_$i.json"
            ${{ github.workspace }}/consolidate-jetstream-results.py intermediate-results.json "results_$i.json"
          fi

          kill "$(pgrep Xvfb)" || true

          sudo snap remove --purge firefox
          sudo snap install firefox

        done

        mv intermediate-results.json "${{ inputs.results-file }}"
