#!/bin/sh

set -e

# shellcheck source=snap-wrap/tests/common.sh
. "${srcdir:-.}/snap-wrap/tests/common.sh"

printf "Test that a non-existing profile causes the launcher to not start"
if ! "$L" snap.name.app /bin/ls >"$TMP/testlog" 2>&1 ; then
   PASS
else
   FAIL
fi
