#!/bin/sh

set -e

# shellcheck source=snap-confine/tests/common.sh
. "${srcdir:-.}/snap-confine/tests/common.sh"

get_common_syscalls >"$TMP"/tmpl
cat >>"$TMP"/tmpl <<EOF
getpriority
EOF

for i in Q_QUOTAON Q_QUOTAOFF Q_GETQUOTA Q_SETQUOTA Q_GETINFO Q_SETINFO Q_GETFMT Q_SYNC Q_XQUOTAON Q_XQUOTAOFF Q_XGETQUOTA Q_XSETQLIM Q_XGETQSTAT Q_XQUOTARM ; do
    cat "$TMP"/tmpl >"$TMP"/snap.name.app
    echo "quotactl $i" >>"$TMP"/snap.name.app

    printf "Test good seccomp arg filtering (quotactl %s)" "$i"
    # ensure that the command "true" can run with the right filter
    if $L snap.name.app /bin/true ; then
        PASS
    else
        dmesg|tail -n1
        FAIL
    fi
done
