#!/bin/sh

set -e

. "${srcdir:-.}/snap-confine/tests/common.sh"

get_common_syscalls >"$TMP"/tmpl
cat >>"$TMP"/tmpl <<EOF
# what we are testing
EOF

for i in 'Q_GETQUOT' 'Q_GETQUOTAA' 'Q_GETQU0TA' ; do
    printf "Test bad seccomp arg filtering (quotactl %s)" "$i"
    cat "$TMP"/tmpl >"$TMP"/snap.name.app
    echo "quotactl $i" >>"$TMP"/snap.name.app

    if $L snap.name.app /bin/true 2>/dev/null; then
        # true returned successfully, bad arg test failed
        cat "$TMP"/snap.name.app
        FAIL
    fi

    # all good
    PASS
done
