#!/bin/sh

set -e

# shellcheck source=snap-confine/tests/common.sh
. "${srcdir:-.}/snap-confine/tests/common.sh"

printf "Test seccomp filter (bad - too long)"

cat >"$TMP"/snap.name.app <<EOF
# some comment
baddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
EOF

if "$L" snap.name.app /bin/true 2>/dev/null; then
    # true returned successfully, length test failed
    FAIL
fi

# all good
PASS
