#!/bin/sh

# Usage:
#   get-mode entry-name /path/to/modeenv
#
# get-mode will look for entry-name in modeenv files and return 0 if
# found, 1 if not found.  It will print the value to stdout.

set -eu

if [ "$#" -gt 2 ]; then
    echo "Too many arguments" 1>&2
    exit 1
fi

if [ "$#" -lt 1 ]; then
    echo "Expected a name as argument" 1>&2
    exit 1
fi

name="${1}"
modeenv="${2:-/run/mnt/data/system-data/var/lib/snapd/modeenv}"

while read -r line; do
  case "${line}" in
    "${name}"=*)
       echo "${line#*=}"
       exit 0
       ;;
    *)
       ;;
  esac
done <"${modeenv}"

exit 1
