set timeout 300

spawn snap create-key another

expect "Passphrase: "
send "pass\n"

expect "Confirm passphrase: "
send "pass\n"

set status [wait]
if {[lindex $status 3] != 0} {
    exit 10
}

set timeout 60

spawn snap keys

expect {
    "another " {}
    timeout { exit 20 }
    eof { exit 30 }
}

set status [wait]
if {[lindex $status 3] != 0} {
    exit 40
}

spawn snap export-key --account=developer another

# fun!
# gpg1 asks for a passphrase on the terminal no matter what
# gpg2 gets the passphrase via our fake pinentry
expect {
    "Enter passphrase: " {send "pass\n"; exp_continue}
    "account-id: developer" {}
    timeout { exit 50 }
    eof { exit 60 }
}

set status [wait]
if {[lindex $status 3] != 0} {
    exit 70
}
