set timeout 60

spawn snap create-key another

expect "Passphrase: "
sleep .5
send "pass\n"

expect "Confirm passphrase: "
sleep .5
send "pass\n"

set status [wait]
if {[lindex $status 3] != 0} {
    exit 1
}

set timeout 60

spawn snap keys

expect {
    "another " {}
    timeout { exit 1 }
    eof { exit 1 }
}

set status [wait]
if {[lindex $status 3] != 0} {
    exit 1
}

spawn snap export-key --account=developer another

# fun!
# gpg1 asks for a passphrase on the terminal no matter what
# gpg2 gets the passphrase via our fake pinentry
expect {
    "Enter passphrase: " {send "pass\n"; exp_continue}
    "account-id: developer" {}
    timeout { exit 1 }
    eof { exit 1 }
}

set status [wait]
if {[lindex $status 3] != 0} {
    exit 1
}
