spawn snap create-key

expect "Passphrase: "
send "pass\n"

expect "Confirm passphrase: "
send "pass\n"

set status [wait]
if {[lindex $status 3] != 0} {
    exit 1
}

set timeout 60

spawn snap keys

expect {
    "default " {}
    timeout { exit 1 }
    eof { exit 1 }
}

set status [wait]
if {[lindex $status 3] != 0} {
    exit 1
}

spawn snap export-key --account=developer default

expect {
    "account-id: developer" {}
    timeout { exit 1 }
    eof { exit 1 }
}

set status [wait]
if {[lindex $status 3] != 0} {
    exit 1
}
