#!/bin/sh

echo "Getting attributes from connect-slot-producer hook"

# Read 'consumer-attr1' attribute of the plug
if ! output=$(snapctl get --plug :producer consumer-attr1); then
    echo "Expected connect-slot-producer be able to read the value of the 'consumer-attr3' attribute of the plug"
    exit 1
fi
expected_output="consumervalue1"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

# Read own 'producer-attr3' attribute
if ! output=$(snapctl get :producer producer-attr3); then
    echo "Expected connect-slot-producer to be able to read the value of own 'producer-attr3' attribute"
    exit 1
fi
expected_output="producervalue3-validated"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

# Read 'consumer-attr3' attribute of the plug
if ! output=$(snapctl get --plug :producer consumer-attr3); then
    echo "Expected connect-slot-producer to be able to read the value of 'consumer-attr3' attribute of the plug"
    exit 1
fi
expected_output="consumervalue3-validated"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

# Failure on unknown slot
if snapctl get :unknown consumer-attr1; then
    echo "Expected snapctl get to fail on unknown slot"
    exit 1
fi

# Attributes cannot be set in connect- hooks
if snapctl set :producer consumer-attr4=foo; then
    echo "Expected snapctl set to fail when run from connect-slot hook"
    exit 1
fi
