#!/bin/sh

echo "Getting attributes from connect-slot-bar hook"

if ! output=$(snapctl get --slot :bar target); then
    echo "Expected connect-slot-bar to be able to read the value of own 'target' attribute"
    exit 1
fi

expected_output="slottarget"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

if snapctl set :bar target=slottarget; then
    echo "Expected snapctl set to fail when run from connect-slot hook"
    exit 1
fi
