#!/bin/sh

echo "Getting attributes from connect-slot-bar hook"

if ! output=$(snapctl iget target); then
    echo "Expected snapctl iget to be able to read the value of 'target' attribute"
    exit 1
fi

expected_output="slottarget"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

if snapctl iset target=slottarget; then
    echo "Expected snapctl iset to fail when run from confirm-plug hook"
    exit 1
fi
