#!/bin/sh
set -x

echo "Getting attributes from disconnect-slot-producer hook"

# Read 'consumer-attr-1' attribute of the plug
if ! output=$(snapctl get --plug :producer consumer-attr-1); then
    echo "Expected connect-slot-producer be able to read the value of the 'consumer-attr-3' attribute of the plug"
    exit 1
fi
expected_output="consumer-value-1"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

# Read own 'producer-attr-3' attribute
if ! output=$(snapctl get :producer producer-attr-3); then
    echo "Expected connect-slot-producer to be able to read the value of own 'producer-attr3' attribute"
    exit 1
fi
expected_output="producer-value-3-validated"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

# Read 'consumer-attr-3' attribute of the plug
if ! output=$(snapctl get --plug :producer consumer-attr-3); then
    echo "Expected connect-slot-producer to be able to read the value of 'consumer-attr-3' attribute of the plug"
    exit 1
fi
expected_output="consumer-value-3-validated"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

# Failure on unknown slot
if snapctl get :unknown consumer-attr-1; then
    echo "Expected snapctl get to fail on unknown slot"
    exit 1
fi

# Attributes cannot be set in connect- or disconnect- hooks
if snapctl set :producer consumer-attr-4=foo; then
    echo "Expected snapctl set to fail when run from connect-slot or disconnect-slot hook"
    exit 1
fi


touch "$SNAP_COMMON/disconnect-slot-producer-done"

