#!/bin/sh

echo "Getting and setting attribute value from prepare-slot-bar hook"

# prepare-slot- hook should be able to read attribute value set by prepare-plug- hook
if ! output=$(snapctl get :foo target); then
    echo "Expected snapctl get to be able to read the value of 'target' attribute"
    exit 1
fi

expected_output="plugtarget"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

# Set own (slot's) 'target' attribute
if ! snapctl set :bar target=slottarget; then
    echo "Expected snapctl set to be able to set the value of 'target' attribute"
    exit 1
fi

# Read own 'target' attribute
if ! output=$(snapctl get :bar target); then
    echo "Expected snapctl get to be able to read the value of 'target' attribute"
    exit 1
fi

expected_output="slottarget"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi
