#!/bin/sh

echo "Getting and setting attribute value from prepare-slot-bar hook"

# prepare-slot- hook should be able to read attribute value set by prepare-plug- hook
if ! output=$(snapctl get-attr target); then
    echo "Expected snapctl get-attr to be able to read the value of 'target' attribute"
    exit 1
fi

expected_output="plugtarget"
if "$output" -ne "$expected_output"; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

if ! snapctl set-attr target=slottarget; then
    echo "Expected snapctl set-attr to be able to set the value of 'target' attribute"
    exit 1
fi

if ! output=$(snapctl get-attr target); then
    echo "Expected snapctl get-attr to be able to read the value of 'target' attribute"
    exit 1
fi

expected_output="slottarget"
if "$output" -ne "$expected_output"; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi
