name: 'Download cached dependencies and install Debian deps'
description: 'Download and install Debian dependencies'
inputs:
  snapd-src-dir:
    description: 'The snapd source code directory'
    required: true
    type: string
  
runs:
  using: "composite"
  steps:
  - name: Download Debian dependencies
    uses: actions/download-artifact@v4
    with:
      name: debian-dependencies
      path: ./debian-deps/

  - name: Copy dependencies
    shell: bash
    run: |
      test -f ./debian-deps/cached-apt.tar
      sudo tar xvf ./debian-deps/cached-apt.tar -C /

  - name: Install Debian dependencies
    shell: bash
    run: |
        sudo apt update
        sudo apt build-dep -y "${{ inputs.snapd-src-dir }}"
        sudo apt install -y clang
        sudo apt install -y gcovr lcov
        rm -rf ./debian-deps
