version: "2"
run:
  concurrency: 4
  tests: true
  allow-parallel-runners: false
linters:
  default: none
  enable:
    - depguard
    - govet
    - ineffassign
    - misspell
    - nakedret
    - testpackage
    - unused
  settings:
    depguard:
      rules:
        osuser:
          files:
            - '!**/osutil/user/*.go'
          deny:
            - pkg: os/user
              desc: Please use osutil/user instead. See https://github.com/canonical/snapd/pull/13776
        testtime:
          files:
            - '!$test'
          deny:
            - pkg: github.com/snapcore/snapd/testtime
              desc: Cannot use testtime outside of test code
            - pkg: github.com/canonical/snapd/testtime
              desc: Cannot use testtime outside of test code
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 10
    lll:
      line-length: 120
      tab-width: 1
    misspell:
      ignore-rules:
        - someword
        - auther
        - PROCES
        - PROCESSS
        - proces
        - processs
        - exportfs
    nakedret:
      max-func-lines: 5
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - deadcode
          - testpackage
        path: export.*_test\.go
      - linters:
          - testpackage
        path: osutil/.*_test.go
      - linters:
          - nakedret
          - testpackage
        path: udev/netlink/.*.go
      - linters:
          - nakedret
          - testpackage
        path: udev/crawler/.*.go
      - linters:
          - testpackage
        path: arch/arch_test.go
      - linters:
          - testpackage
        path: asserts/findwildcard_test.go
      - linters:
          - testpackage
        path: cmd/snapctl/main_test.go
      - linters:
          - testpackage
        path: cmd/snap-update-ns/sorting_test.go
      - linters:
          - testpackage
        path: daemon/daemon_test.go
      - linters:
          - testpackage
        path: daemon/ucrednet_test.go
      - linters:
          - testpackage
        path: i18n/i18n_test.go
      - linters:
          - testpackage
        path: i18n/xgettext-go/main_test.go
      - linters:
          - testpackage
        path: interfaces/builtin/common_test.go
      - linters:
          - testpackage
        path: interfaces/hotplug/deviceinfo_test.go
      - linters:
          - testpackage
        path: interfaces/hotplug/proposed_slot_test.go
      - linters:
          - testpackage
        path: interfaces/hotplug/udevadm_test.go
      - linters:
          - testpackage
        path: overlord/hookstate/context_test.go
      - linters:
          - testpackage
        path: overlord/hookstate/repository_test.go
      - linters:
          - testpackage
        path: overlord/snapstate/cookies_test.go
      - linters:
          - testpackage
        path: overlord/snapstate/progress_test.go
      - linters:
          - testpackage
        path: polkit/pid_start_time_test.go
      - linters:
          - testpackage
        path: snap/snapenv/snapenv_test.go
      - linters:
          - testpackage
        path: snap/types_test.go
      - linters:
          - testpackage
        path: store/details_v2_test.go
      - linters:
          - testpackage
        path: store/stringlist_test.go
      - linters:
          - testpackage
        path: strutil/shlex/shlex_test.go
      - linters:
          - testpackage
        path: tests/lib/fakestore/store/store_test.go
      - linters:
          - testpackage
        path: testutil/exec_test.go
      - linters:
          - testpackage
        path: timeout/timeout_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  new: false
formatters:
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/snapcore/snapd
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
