ignore_files:
  - build-aux/snap/local/apparmor/apparmor-parser-fix-protocol-error-on-older-kernels-caused-by.patch
  - build-aux/snap/local/apparmor/parser-add-support-for-prompting.patch
  - cmd/libsnap-confine-private/snap.c
  - cmd/libsnap-confine-private/string-utils-test.c
  - cmd/libsnap-confine-private/string-utils-test.c
  - cmd/libsnap-confine-private/string-utils.c
  - cmd/snap-confine/snap-confine.apparmor.in
  - cmd/snap-confine/snap-confine.c
  - osutil/mount/libmount/libmount_linux.go
  - osutil/mount/libmount/libmount_linux_test.go
  - packaging/debian-sid/changelog
  - packaging/fedora/snapd.spec
  - packaging/ubuntu-14.04/changelog
  - packaging/ubuntu-16.04/changelog
  - tests/lib/snaps/store/test-snapd-ovmf/snapcraft.yaml
