SUBDIRS = cmd data

prefix = /usr
bindir = $(prefix)/bin
libdir = $(prefix)/lib
libexecdir = $(prefix)/lib
libexecsnapddir = $(libexecdir)/snapd
datadir = $(prefix)/share
srcdir = $(realpath .)

BUILD_CONFIG_FILE = build-config
STATIC_LIBCAP ?= 0
SECCOMP ?= 1
STATIC_LIBSECCOMP ?= 0
APPARMOR ?= 0
STATIC_LIBAPPARMOR ?= 0
MERGED_USR = 0
NVIDIA_BIARCH = 0
NVIDIA_MULTIARCH = 0
CAPS_OVER_SETUID = 0
LIB32_DIR = $(prefix)/lib32
SNAPD_ENVIRONMENT_FILE = /etc/environment
SNAP_MOUNT_DIR = /snap
HOST_ARCH_TRIPLET =
HOST_ARCH_32BIT_TRIPLET =

define for_all =
for d in $(SUBDIRS); do \
	$(MAKE) -C $$d $(MAKEFLAGS) $(MAKECMDGOALS) || break; \
done
endef

.PHONY: clean distclean all install
all clean distclean install:
	@if [ ! -e $(BUILD_CONFIG_FILE) ]; then \
		echo "run make configure first"; false ; \
	fi
	$(for_all)

.PHONY: configure
configure:
	echo "# autogenerated by make $@" > $(BUILD_CONFIG_FILE)
	echo "prefix = $(prefix)" >> $(BUILD_CONFIG_FILE)
	echo "bindir = $(bindir)" >> $(BUILD_CONFIG_FILE)
	echo "libdir = $(libdir)" >> $(BUILD_CONFIG_FILE)
	echo "libexecdir = $(libexecdir)" >> $(BUILD_CONFIG_FILE)
	echo "libexecsnapddir = $(libexecsnapddir)" >> $(BUILD_CONFIG_FILE)
	echo "datadir = $(datadir)" >> $(BUILD_CONFIG_FILE)
	echo "srcdir = $(srcdir)" >> $(BUILD_CONFIG_FILE)
	echo "SNAP_MOUNT_DIR = $(SNAP_MOUNT_DIR)" >> $(BUILD_CONFIG_FILE)
	echo "STATIC_LIBCAP = $(STATIC_LIBCAP)" >> $(BUILD_CONFIG_FILE)
	echo "SECCOMP = $(SECCOMP)" >> $(BUILD_CONFIG_FILE)
	echo "STATIC_LIBSECCOMP = $(STATIC_LIBSECCOMP)" >> $(BUILD_CONFIG_FILE)
	echo "APPARMOR = $(APPARMOR)" >> $(BUILD_CONFIG_FILE)
	echo "STATIC_LIBAPPARMOR = $(STATIC_LIBAPPARMOR)" >> $(BUILD_CONFIG_FILE)
	echo "MERGED_USR = $(MERGED_USR)" >> $(BUILD_CONFIG_FILE)
	echo "NVIDIA_BIARCH = $(NVIDIA_BIARCH)" >> $(BUILD_CONFIG_FILE)
	echo "NVIDIA_MULTIARCH = $(NVIDIA_MULTIARCH)" >> $(BUILD_CONFIG_FILE)
	echo "HOST_ARCH_TRIPLET = $(HOST_ARCH_TRIPLET)" >> $(BUILD_CONFIG_FILE)
	echo "HOST_ARCH32_TRIPLET = $(HOST_ARCH_32BIT_TRIPLET)" >> $(BUILD_CONFIG_FILE)
	echo "CAPS_OVER_SETUID = $(CAPS_OVER_SETUID)" >> $(BUILD_CONFIG_FILE)
	echo "LIB32_DIR = $(LIB32_DIR)" >> $(BUILD_CONFIG_FILE)
	echo "SNAPD_ENVIRONMENT_FILE = $(SNAPD_ENVIRONMENT_FILE)" >> $(BUILD_CONFIG_FILE)
