option('selinux', type : 'boolean', value : false)
option('apparmor', type : 'boolean', value : true)
option('snapmountdir', type : 'string', value : '/snap')
option('snapd_environment_file', type : 'string', value : '/etc/environment')
option('envd', type : 'string', value : '/usr/lib/environment.d')
option('core', type : 'boolean', value : false)
option('dracut', type : 'feature', value : 'auto')
option('test-keys', type : 'boolean', value : false)
option('secboot', type : 'boolean', value : false)
option('unit-tests', type : 'feature', value : 'auto')
option('vendor-dist', type : 'boolean', value : true)
option('vendored', type : 'feature', value : 'auto')
option('bpf', type : 'feature', value : 'auto')
option('optee', type : 'boolean', value : false)
option('usergo', type : 'boolean', value : false)
option('setcap', type : 'boolean', value : true)
option('apparmorconfigdir', type : 'string', value : '/etc/apparmor.d')
option('gopath', type : 'string')
option('goldflags', type : 'string')
option('gotags', type : 'string')
option('nvidia-biarch', type : 'boolean', value : false)
option('nvidia-multiarch', type : 'boolean', value : false)
option('32bit-libdir', type : 'string')
