#!/bin/sh
set -e

GO_GENERATE_BUILDDIR="$(pwd)"

# run from "go generate" adjust path
if [ "$GOPACKAGE" = "release" ]; then
    GO_GENERATE_BUILDDIR="$(pwd)/.."
fi

stamp="$(cat /proc/sys/kernel/random/uuid)"
echo "*** Setting build-stamp to '$v'." >&2

cat <<EOF > "$GO_GENERATE_BUILDDIR/release/release_generated.go"
package release

// generated by mkbuild-stamp.sh; do not edit

func init() {
	BuildStamp = "$stamp"
}
EOF

