#!/bin/bash

# check dependencies
if ! snap list snapcraft &>/dev/null; then
    echo "snapcraft is not installed"
    exit 1
fi

# Clean the snaps created in previous runs
touch test-build
rm -rf built-snap
mkdir built-snap
rm -f snapd_1337.*.snap snapd_1337.*.snap.keep

# Build snapd snap
snapcraft --use-lxd
for snap in built-snap/snapd_1337.*.snap; do
    mv "${snap}" "${snap}.keep"
done

# Run spread
spread "$@"
