#!/bin/sh
# -*- Mode: sh; indent-tabs-mode: t -*-

set -e

HERE="$(dirname $0)"

OUTPUT="$HERE/po/snappy.pot"
if [ -n "$1" ]; then
	OUTPUT="$1"
fi

# ensure we have our xgettext-go
go install github.com/snapcore/snapd/i18n/xgettext-go

$GOPATH/bin/xgettext-go \
    -o "$OUTPUT" \
    --add-comments-tag=TRANSLATORS: \
    --no-location \
    --sort-output \
    --package-name=snappy\
    --msgid-bugs-address=snappy-devel@lists.ubuntu.com \
    --keyword=i18n.G \
    --keyword-plural=i18n.DG \
    $(find $HERE -name "*.go" -type f)

#xgettext -d snappy -o "$OUTPUT" --c++ --from-code=UTF-8 \
#	--indent --add-comments=TRANSLATORS: --no-location --sort-output \
#	--package-name=snappy \
#	--msgid-bugs-address=snappy-devel@lists.ubuntu.com \
#	--keyword=NG:1,2 --keyword=G \
#	$HERE/*/*.go $HERE/cmd/*/*.go

# language packs
for p in ${HERE}/po/*.po; do
	lang=$(basename $p .po)
	mkdir -p $HERE/share/locale/$lang/LC_MESSAGES
	msgfmt -v -o $HERE/share/locale/$lang/LC_MESSAGES/snappy.mo $p 
done
