#!/bin/bash

set -eu

case "${1}" in
     get)
         if ! [ -f "${MESON_SOURCE_ROOT}/cmd/VERSION" ]; then
             (cd "${MESON_SOURCE_ROOT}"; ./mkversion.sh)
         fi
         cat "${MESON_SOURCE_ROOT}/cmd/VERSION"
         ;;
     set)
         echo "${2}" >"${MESON_DIST_ROOT}/cmd/VERSION"
         # FIXME: split packaging/gen-version.sh so it does not do data/info
         cat <<EOF > "${MESON_DIST_ROOT}/snapdtool/version_generated.go"
package snapdtool

// generated by version.sh; do not edit

func init() {
	UpstreamVersion = "${2}"
}
EOF
         ;;
     *)
         exit 1
         ;;
esac
