#!/bin/sh

set -ex

# required for the debian adt host
mkdir -p /etc/systemd/system/snapd.service.d/ 
if [ "$http_proxy" != "" ]; then
    cat <<EOF | tee /etc/systemd/system/snapd.service.d/proxy.conf
[Service]
Environment=http_proxy=$http_proxy
Environment=https_proxy=$http_proxy
EOF

    # ensure environment is updated
    echo "http_proxy=$http_proxy" >> /etc/environment
    echo "https_proxy=$http_proxy" >> /etc/environment
fi
systemctl daemon-reload

# ensure we can do a connect to localhost
echo ubuntu:ubuntu|chpasswd
sed -i 's/\(PermitRootLogin\|PasswordAuthentication\)\>.*/\1 yes/' /etc/ssh/sshd_config

service ssh restart

# and now run spread against localhost
. /etc/os-release
apt-get install golang-1.6-go
export GOPATH=/tmp/go
export PATH=/usr/lib/go-1.6/bin:${PATH}
go get -u github.com/snapcore/spread/cmd/spread
/tmp/go/bin/spread -v autopkgtest:${ID}-${VERSION_ID}-$(dpkg --print-architecture)
