#!/bin/bash -e

shopt -s nullglob

# check dependencies
if ! snap list snapcraft >/dev/null; then
    echo "snapcraft is not installed"
    exit 1
fi

# Clean the snaps created in previous runs
rm -rfv built-snap

find . -name 'snapd_1337.*.snap' -print0 | xargs -0 -- rm -fv
find . -name 'snapd_1337.*.snap.keep' -print0 | xargs -0 -- rm -fv

touch test-build
mkdir -p built-snap

# Build snapd snap
if [ -z "$SNAPCRAFT_NO_CLEAN" ]; then
    snapcraft --verbose clean
fi

snapcraft --verbose

for snap_file in snapd_1337.*.snap; do
    mv "${snap_file}" built-snap/"${snap_file}.keep"
done

rm -fv test-build
