#!/bin/sh

set -e

arch=`dpkg --print-architecture`
if [ "$arch" != "amd64" ] && [ "$arch" != "i386" ]; then
    printf "Tests will only work on amd64\n"
    exit 0
fi

run-parts --regex '^test_[a-z_]+$' .
