#!/bin/sh

set -e

export UBUNTU_CORE_LAUNCHER_NO_ROOT=1

if [ "$(dpkg --print-architecture)" != "amd64" ]; then
    printf "Tests will only work on amd64\n"
    exit 0
fi

run-parts --regex '^test_[a-z_]+$' .
