#!/bin/sh

set -e

. "$(pwd)"/common.sh

cat >"$TMP"/tmpl <<EOF
# the ones we must have
open
close
mmap
munmap
mprotect
fstat
access
read
brk
execve
arch_prctl
exit_group
geteuid
getuid

# what we are testing
EOF

for i in 'AF_UNI' 'AF_UNIXX' 'AF_UN!X' ; do
    printf "Test bad seccomp arg filtering (socket %s)" "$i"
    cat "$TMP"/tmpl >"$TMP"/myprofile
    echo "socket $i" >>"$TMP"/myprofile

    if $L snap.name.app myprofile /bin/true 2>/dev/null; then
        # true returned successfully, bad arg test failed
        cat "$TMP"/myprofile
        FAIL
    fi

    # all good
    PASS
done

for i in 'SOCK_STREA' 'SOCK_STREAMM' ; do
    printf "Test bad seccomp arg filtering (socket - %s)" "$i"
    cat "$TMP"/tmpl >"$TMP"/myprofile
    echo "socket - $i" >>"$TMP"/myprofile

    if $L snap.name.app myprofile /bin/true 2>/dev/null; then
        # true returned successfully, bad arg test failed
        cat "$TMP"/myprofile
        FAIL
    fi

    # all good
    PASS
done
