#!/bin/sh

set -e

. $(pwd)/common.sh

printf "Test appname whitelist"

cat >$TMP/myprofile <<EOF
# some comment
@unrestricted
EOF

# good
$L appname myprofile /bin/true
$L pkg.binary myprofile /bin/true
$L pkg-foo.0binary-bar+baz myprofile /bin/true
$L network-manager.NetworkManager myprofile /bin/true

# and now the bad ones
if $L appname/.. myprofile /bin/true 2>/dev/null; then
    # true returned successfully, our appname whitelist is broken!
   FAIL
fi

if $L 'appname space' myprofile /bin/true 2>/dev/null; then
    # true returned successfully, our appname whitelist is broken!
   FAIL
fi

# all good
PASS
