#!/bin/sh

set -e

. "$(pwd)"/common.sh

cat >"$TMP"/tmpl <<EOF
# the ones we must have
open
close
mmap
munmap
mprotect
fstat
access
read
brk
execve
arch_prctl
exit_group
geteuid
getuid

# what we are testing
EOF

for i in 'PRIO_PROCES' 'PRIO_PROCESSS' 'PRIO_PR0CESS'; do
    printf "Test bad seccomp arg filtering (setpriority %s 0 >= 0)" "$i"
    cat "$TMP"/tmpl >"$TMP"/snap.name.app
    echo "setpriority $i 0 >=0" >>"$TMP"/snap.name.app

    if $L snap.name.app /bin/true 2>/dev/null; then
        # true returned successfully, bad arg test failed
        cat "$TMP"/snap.name.app
        FAIL
    fi

    # all good
    PASS
done
