#!/bin/sh

set -e

. "${srcdir:-.}/common.sh"

cat >"$TMP/snap.name.app" <<EOF
@unrestricted
EOF

cat >"$TMP/snap.name.fstab" <<EOF
/src /dst none bind 0 0
EOF

printf "Test that bind mounts work "
"$L" snap.name.app /bin/true
PASS