#!/bin/sh

set -e

. $(pwd)/common.sh

printf "Test seccomp filter (bad - no trailing newline)"

echo -n "missingnewline" > $TMP/aaprofile

if $L appname aaprofile /bin/true 2>/dev/null; then
    # true returned successfully, length test failed
    FAIL
fi

# all good
PASS
