#!/bin/sh

set -e

. "$(pwd)"/common.sh

cat >"$TMP"/tmpl <<EOF
# the ones we must have
open
close
mmap
munmap
mprotect
fstat
access
read
brk
execve
arch_prctl
exit_group
geteuid
getuid

# what we are testing
EOF

# Test these individually since you can't store \0 in a variable
printf "Test bad seccomp arg filtering (socket S\\\0CK_STREAM)"
cat "$TMP"/tmpl >"$TMP"/myprofile
printf "socket S\0CK_STREAM\n" >>"$TMP"/myprofile

if $L snap.name.app myprofile /bin/true 2>/dev/null; then
    # true returned successfully, bad arg test failed
    cat "$TMP"/myprofile
    FAIL
else
    PASS
fi

# an embedded null that is after a valid arg stops processing of the arg
# (limitation of fgets() implementation)
printf "Test ok seccomp arg filtering (socket SOCK_STREAM\\\0bad stuff)"
cat "$TMP"/tmpl >"$TMP"/myprofile
printf "socket SOCK_STREAM\0bad stuff\n" >>"$TMP"/myprofile

if $L snap.name.app myprofile /bin/true 2>/dev/null; then
    PASS
else
    cat "$TMP"/myprofile
    FAIL
fi
