#!/bin/sh

set -e

. $(pwd)/common.sh

printf "Test seccomp filter (bad - too long)"

cat >$TMP/myprofile <<EOF
# some comment
baddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
EOF

if $L appname myprofile /bin/true 2>/dev/null; then
    # true returned successfully, length test failed
    FAIL
fi

# all good
PASS
