#!/bin/sh

set -e

. $(pwd)/common.sh

cat >$TMP/snap.name.app <<EOF
# filter that works ok for true
open
close

mmap
munmap
mprotect

fstat
access
read

brk
execve

arch_prctl
exit_group

geteuid
getuid

# unknown syscalls are ignore
i-dont-exit

less-than-SC_MAX_LINE_LENGTH-but-still-looooooooooooooonnnnnnnngggggggggggggggg
EOF

# ensure that the command "true" can run with the right filter

printf "Test that good whitelist"
if $L snap.name.app /bin/true 2>/dev/null; then
   PASS
else
    dmesg|tail -n1
    FAIL
fi
