// -*- Mode: Go; indent-tabs-mode: t -*-

/*
 * Copyright (C) Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package ldconfig_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	. "gopkg.in/check.v1"

	"github.com/snapcore/snapd/dirs"
	"github.com/snapcore/snapd/interfaces"
	"github.com/snapcore/snapd/interfaces/ifacetest"
	"github.com/snapcore/snapd/interfaces/ldconfig"
	"github.com/snapcore/snapd/snap"
	"github.com/snapcore/snapd/testutil"
)

func Test(t *testing.T) {
	TestingT(t)
}

type backendSuite struct {
	ifacetest.BackendSuite
	ldconfigCmd *testutil.MockCmd
}

var _ = Suite(&backendSuite{})

func (s *backendSuite) SetUpTest(c *C) {
	s.Backend = &ldconfig.Backend{}
	s.BackendSuite.SetUpTest(c)
	c.Assert(s.Repo.AddBackend(s.Backend), IsNil)
	s.ldconfigCmd = testutil.MockCommand(c, "ldconfig", "")
}

func (s *backendSuite) TearDownTest(c *C) {
	s.ldconfigCmd.Restore()
	s.BackendSuite.TearDownTest(c)
}

func (s *backendSuite) TestName(c *C) {
	c.Check(s.Backend.Name(), Equals, interfaces.SecurityLdconfig)
}

func checkLdconfigFile(c *C, snapName, slot string, libDirs []string) {
	path := filepath.Join(dirs.GlobalRootDir, "etc", "ld.so.conf.d",
		fmt.Sprintf("snap.%s.%s.conf", snapName, slot))
	content := "# This file is automatically generated by snapd\n"
	content += strings.Join(libDirs, "\n")
	content += "\n"
	c.Assert(path, testutil.FileEquals, content)
}

func (s *backendSuite) TestInstallingCreatesLdconf(c *C) {
	s.Iface.LdconfigPermanentSlotCallback = func(spec *ldconfig.Specification,
		slot *snap.SlotInfo) error {
		spec.AddLibDirs("snap1", "slot1", []string{"/dir1/lib1", "/dir1/lib11"})
		spec.AddLibDirs("snap1", "slot2", []string{"/dir1/lib2", "/dir1/lib22"})
		spec.AddLibDirs("snap2", "slot1", []string{"/dir2/lib1"})
		return nil
	}
	snapInfo := s.InstallSnap(c, interfaces.ConfinementOptions{}, "", ifacetest.SambaYamlV1, 0)

	confDir := filepath.Join(dirs.GlobalRootDir, "etc", "ld.so.conf.d")
	libcConfPath := filepath.Join(confDir, "libc.conf")
	c.Assert(os.WriteFile(libcConfPath, []byte{}, 0644), IsNil)

	checkLdconfigFile(c, "snap1", "slot1", []string{"/dir1/lib1", "/dir1/lib11"})
	checkLdconfigFile(c, "snap1", "slot2", []string{"/dir1/lib2", "/dir1/lib22"})
	checkLdconfigFile(c, "snap2", "slot1", []string{"/dir2/lib1"})

	c.Assert(s.ldconfigCmd.Calls(), DeepEquals, [][]string{
		{"ldconfig"},
	})
	s.ldconfigCmd.ForgetCalls()

	// When refreshing a slot is removed
	s.Iface.LdconfigPermanentSlotCallback = func(spec *ldconfig.Specification,
		slot *snap.SlotInfo) error {
		spec.AddLibDirs("snap1", "slot1", []string{"/dir1/lib1", "/dir1/lib11"})
		spec.AddLibDirs("snap2", "slot1", []string{"/dir2/lib1"})
		return nil
	}
	s.UpdateSnap(c, snapInfo, interfaces.ConfinementOptions{}, ifacetest.SambaYamlV1, 1)

	checkLdconfigFile(c, "snap1", "slot1", []string{"/dir1/lib1", "/dir1/lib11"})
	c.Check(filepath.Join(confDir, "snap.snap1.slot2.conf"), testutil.FileAbsent)
	checkLdconfigFile(c, "snap2", "slot1", []string{"/dir2/lib1"})

	c.Assert(s.ldconfigCmd.Calls(), DeepEquals, [][]string{
		{"ldconfig"},
	})

	// libc config has not been touched
	c.Check(libcConfPath, testutil.FilePresent)

	s.RemoveSnap(c, snapInfo)
}

func (s *backendSuite) TestSandboxFeatures(c *C) {
	c.Assert(s.Backend.SandboxFeatures(), DeepEquals, []string{"mediated-ldconfig"})
}
