#!/usr/bin/env python3

import dbus
import os
import sys

INTERFACE = 'org.freedesktop.DBus.Properties'
PATH = '/com/ubuntu/location/Service'


def _get_obj():
    return dbus.SystemBus().get_object(INTERFACE, PATH)


def get(property_name):
    obj = _get_obj()
    return obj.Get(dbus_interface=INTERFACE, property_name=property_name)


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "Get":
        res = get('test')
        print(res)
    else:
        print('Method not supported')
        exit(1)
