#!/usr/bin/env python3

import dbus
import os
import sys

INTERFACE = 'com.ubuntu.location.Service'
PATH = '/com/ubuntu/location/Service'


def _get_obj():
    return dbus.SystemBus().get_object(INTERFACE, PATH)


def get():
    obj = _get_obj()
    return obj.Get(dbus_interface=INTERFACE)


def set():
    obj = _get_obj()
    return obj.Set(dbus_interface=INTERFACE)


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "Set":
        res = set()
    else:
        res = get()

    print(res)
