name: Combine results
description: | 
  Determines a single result from one or more results. A single skipped or
  failed will cause the action to fail. Details for each job will be output 
  as part of a results summary.

inputs:
  needs-json:
    description: Job outputs in JSON format
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: Summarise and combine results
    shell: bash
    run: |
      # From https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#jobs-context
      # Possible results are success, failed, cancelled, and skipped
      needs_results=$(echo '${{ inputs.needs-json }}' | jq -r 'to_entries[] | "\(.key) \(.value.result)"')

      echo "Summary:"
      failed="false"
      while IFS=" " read -r job result; do
        if [[ "$result" == "success" ]]; then
          echo "- ✅ Job \"$job\" returned result \"$result\""
        else
          failed="true"
          echo "- ❌ Job \"$job\" returned result \"$result\""
        fi
      done <<< "$needs_results"
      
      if [[ "$failed" == "false" ]]; then
        echo "Overall result: success"
      else
        echo "Overall result: failure"
        exit 1
      fi 
