#!/bin/sh

set -ex

# for these tests, run snap and snapd from outside of the core snap
mkdir -p /etc/systemd/system/snapd.service.d/
cat <<EOF | tee /etc/systemd/system/snapd.service.d/no-reexec.conf
[Service]
Environment=SNAP_REEXEC=0
EOF

# required for the debian adt host
if [ "$http_proxy" != "" ]; then
    cat <<EOF | tee /etc/systemd/system/snapd.service.d/proxy.conf
[Service]
Environment=http_proxy=$http_proxy
Environment=https_proxy=$http_proxy
EOF
fi
systemctl daemon-reload

# ensure our PATH is right
. /etc/profile.d/apps-bin-path.sh


# debug
cat /etc/ssh/sshd_config
id
grep ubuntu /etc/passwd

# ensure we can do a connect to localhost
echo ubuntu:ubuntu|chpasswd
sed -i 's/\(PermitRootLogin\|PasswordAuthentication\)\>.*/\1 yes/' /etc/ssh/sshd_config


# ensure we can run spread
export GOPATH=/tmp/go
go get -u github.com/snapcore/spread/cmd/spread
/tmp/go/bin/spread -v adhoc:
