package snappy

import (
	. "launchpad.net/gocheck"
)

// systemd's testsuite
type DBusTestSuite struct {
	busName string
}

var _ = Suite(&DBusTestSuite{})

func (s *DBusTestSuite) SetUpTest(c *C) {
	s.busName = "foo.bar.baz"
}

const expectedBusPolicy = `<?xml version="1.0"?> <!--*-nxml-*-->
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
        "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">

<!--
  This file is autogenerated by snappy
-->

<busconfig>
        <policy user="root">
                <allow own="foo.bar.baz"/>
                <allow send_destination="foo.bar.baz"/>
        </policy>

        <policy context="default">
                <allow send_destination="foo.bar.baz"/>
        </policy>
</busconfig>
`

func (s *DBusTestSuite) TestGenBusPolicyFile(c *C) {
	generated, err := genBusPolicyFile(s.busName)
	c.Assert(err, Equals, nil)
	c.Assert(generated, Equals, expectedBusPolicy)
}
