source "$::env(SPREAD_PATH)/$::env(SPREAD_SUITE)/lib.exp0"
send "source $::env(SPREAD_PATH)/$::env(SPREAD_SUITE)/$::env(SPREAD_VARIANT).sh\n"
next
send "source /usr/share/bash-completion/bash_completion\n"
next
if {$::env(_COMPLETE_SH)} {
    # because this sources complete.sh, it won't be using the snippets
    send "source $::env(SPREAD_PATH)/data/completion/complete.sh\n"
    next
}
chat "$::env(CMD) \t\t" $::env(_OUT0)
cancel
# completion when the cursor is not at the end of the line:
set back1 [string repeat "\b" [string length $::env(_KEY1)]]
chat "$::env(CMD) $::env(_KEY1)$back1\t\t" $::env(_OUT0)
cancel
chat "$::env(CMD) $::env(_KEY1)\t" $::env(_OUT1)
cancel
chat "$::env(CMD) $::env(_KEY2)\t\t" $::env(_OUT2)
cancel
brexit
