source lib.exp0

# install completes directories and snaps
chat "snap ins\t./\t\t" "bar.snap*testdir/"
cancel

# install also completes store stuff
chat "snap install tes\t\t\t" "test-assumes" true
# TODO: don't list things already installed:
chat "" "test-snapd-tools" true
chat "" "testdir/"
cancel

# no extra space added after a directory
chat "snap ins\t./tes\t" " ./testdir/$"
cancel

# extra space added after a file
chat "snap ins\t./bar\t" " ./bar.snap $"

cancel
brexit
