#!/usr/bin/env python3

import os
import subprocess
import json

def _snapctl(action : str, settings : list[str]):
    args = ["snapctl", action]
    args.extend(settings)

    snapctl = subprocess.run(
        args,
        capture_output=True,
        text=True,
    )

    if snapctl.returncode != 0:
        return ''

    output = snapctl.stdout
    if action == "get" and output[-1] == '\n':
        output = output[:-1]

    return output

cmd = f"snapctl get --view :topic-control -d"
proc = subprocess.run(cmd.split(), capture_output=True, text=True)
if proc.returncode != 0:
    cmd = f"snapctl fail {proc.stderr}"
    subprocess.run(cmd.split())
    exit(1)

config = json.loads(proc.stdout)

for snap, topics in config.items():
    # check that snap is installed
    snapPath = os.path.join("/snap", snap)
    if not os.path.exists(snapPath):
        err = f"snap {snap} is not installed"
        cmd = f"snapctl fail {err}"
        subprocess.run(cmd.split())
        print(err)
        exit(1)        

_snapctl("restart", ["telem-agent"])
