#!/usr/bin/expect

set timeout 2

# test allowed access
spawn sudo -i -u test /bin/sh -c /snap/bin/test-snapd-tools.sh
expect "bash-4.3$"
send "touch /dev/shm/snap.test-snapd-tools.foo"
send"stat /tmp/foo"
expect "File: '/tmp/foo'"

# test that /tmp/foo is not accessible to other apps
spawn sudo -i -u test /bin/sh -c /snap/bin/not-test-snapd-tools.sh
expect "bash-4.3$"
send "stat /tmp/foo"
expect "stat: cannot stat '/tmp/foo': No such file or directory"
