#!/bin/sh -e

# start running
snapctl start --enable "$SNAP_NAME.svc"

# wait a bit, the service is only creating a file, so we don't need to bother
# ourselves with waiting too long
sleep 5

# stop running
snapctl stop --disable "$SNAP_NAME.svc"
