#!/bin/bash

# This script must be run from the base of the snapd repo directory
# Input is the desired spread command to run with feature tagging
#	ex: ./tests/utils/tag-features qemu:ubuntu-24.04-64:tests/main/

set -xeu

if [ -z "${SPREAD_TAG_FEATURES:-}" ]; then
	echo "since SPREAD_TAG_FEATURES was not set, tagging all features by default"
	export SPREAD_TAG_FEATURES="all"
fi


WRITE_DIR="/tmp/features"
RUN_TESTS=("$@")
NUM_ATTEMPTS=${NUM_ATTEMPTS:-1}
export SPREAD_USE_PREBUILT_SNAPD_SNAP=true
mkdir -p "$WRITE_DIR"
for i in $(seq 1 "$NUM_ATTEMPTS"); do

	spread -artifacts "${WRITE_DIR}"/features-artifacts -no-debug-output "${RUN_TESTS[@]}" | tee "${WRITE_DIR}/spread-logs.txt"

	if [ -f "$WRITE_DIR"/spread-logs.txt ]; then
		./tests/lib/external/snapd-testing-tools/utils/log-parser "${WRITE_DIR}"/spread-logs.txt --output "${WRITE_DIR}"/spread-results.json
		./tests/lib/external/snapd-testing-tools/utils/log-analyzer list-reexecute-tasks "${RUN_TESTS[*]}" "${WRITE_DIR}"/spread-results.json >"${WRITE_DIR}"/failed-tests.txt
	else
		touch "${WRITE_DIR}/failed-tests.txt"
	fi

	IFS=',' read -ra features <<< "${SPREAD_TAG_FEATURES}"
	featdir="${WRITE_DIR}/extracted-tags"
	mkdir -p "$featdir"
	for dir in "${WRITE_DIR}"/features-artifacts/feature-tags/*/; do
		if [ -f "${dir}/journal.txt" ] && [ -f "${dir}/state.json" ]; then
			./tests/utils/features/featextractor.py \
				-f "${features[@]}" \
				--journal "${dir}/journal.txt" \
				--state "${dir}/state.json" \
				--output "$featdir/$(basename "${dir}")"
		fi
	done

	./tests/utils/features/featcomposer.py \
		--dir ${featdir} \
		--output ${WRITE_DIR}/composed-feature-tags \
		--failed-tests "$(cat ${WRITE_DIR}/failed-tests.txt)" \
		--run-attempt "${i}"

	if [ ! -s "${WRITE_DIR}/failed-tests.txt" ]; then
		break
	fi

	mapfile RUN_TESTS <"${WRITE_DIR}"/failed-tests.txt
done

./tests/utils/features/featcomposer.py \
	--dir ${WRITE_DIR}/composed-feature-tags \
	--output ${WRITE_DIR}/final-feature-tags \
	--replace-old-runs

echo "Your feature tags can be found in $WRITE_DIR/final-feature-tags"

