# apt hook
data/apt/20snapd.conf /etc/apt/apt.conf.d/
usr/lib/snapd/complete.sh
usr/lib/snapd/etelpmoc.sh
# bash completion
usr/share/bash-completion/completions/snap
# zsh completion
usr/share/zsh/vendor-completions/_snap
# snap/snapd version information
usr/lib/snapd/info
# snap-confine stuff
etc/apparmor.d/usr.lib.snapd.snap-confine.real
usr/lib/snapd/snapd
usr/lib/snapd/snap-seccomp
usr/lib/snapd/snap-update-ns
usr/lib/snapd/snapctl
usr/lib/snapd/snap-confine
usr/lib/snapd/snap-confine.caps
usr/lib/snapd/snap-confine.v2-only.caps
usr/lib/snapd/snap-device-helper
usr/lib/snapd/snap-discard-ns
usr/lib/snapd/snapd-tool-wrap
# gdb helper
usr/lib/snapd/snap-gdbserver-shim
usr/lib/snapd/snap-strace-shim
usr/lib/snapd/snap-mgmt
# use "usr/lib" here because apparently systemd looks only there
usr/lib/systemd/system-environment-generators
usr/lib/systemd/system-generators
usr/share/man/
# upstream changelog
usr/share/doc/snapd/NEWS.md

usr/bin/snapctl
usr/lib/snapd/snap-exec
usr/bin/snap
usr/lib/snapd/snap-preseed
usr/lib/snapd/snapd-apparmor
usr/lib/snapd/snap-gpio-helper

etc/profile.d/snapd.sh
etc/xdg/autostart/snap-userd-autostart.desktop
usr/lib/dracut/dracut.conf.d/50-snapd.conf
usr/lib/environment.d/990-snapd.conf
usr/lib/snapd/snap-mgmt-selinux
usr/lib/snapd/snapd.run-from-snap
usr/lib/systemd/system/snapd.apparmor.service
usr/lib/systemd/system/snapd.mounts-pre.target
usr/lib/systemd/system/snapd.mounts.target
usr/lib/systemd/system/snapd.seeded.service
usr/lib/systemd/system/snapd.service
usr/lib/systemd/system/snapd.socket
usr/lib/systemd/user/snapd.session-agent.service
usr/lib/systemd/user/snapd.session-agent.socket
usr/lib/tmpfiles.d/snapd.conf
usr/share/applications/io.snapcraft.SessionAgent.desktop
usr/share/applications/snap-handle-link.desktop
usr/share/dbus-1/services/io.snapcraft.Launcher.service
usr/share/dbus-1/services/io.snapcraft.SessionAgent.service
usr/share/dbus-1/services/io.snapcraft.Settings.service
usr/share/dbus-1/session.d/snapd.session-services.conf
usr/share/dbus-1/system.d/snapd.system-services.conf
usr/share/fish/vendor_conf.d/snapd.fish
usr/share/polkit-1/actions/io.snapcraft.snapd.policy
usr/share/snapd/snapcraft-logo-bird.svg
