// -*- Mode: Go; indent-tabs-mode: t -*-

/*
 * Copyright (C) 2017 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package builtin

import (
	"fmt"

	"github.com/snapcore/snapd/interfaces"
	"github.com/snapcore/snapd/interfaces/apparmor"
	"github.com/snapcore/snapd/interfaces/udev"
)

const opticalDriveSummary = `allows read access to optical drives`

const opticalDriveBaseDeclarationSlots = `
  optical-drive:
    allow-installation:
      slot-snap-type:
        - core
`

const opticalDriveConnectedPlugAppArmor = `
/dev/sr[0-9]* r,
/dev/scd[0-9]* r,
@{PROC}/sys/dev/cdrom/info r,
`

const opticalDriveConnectedPlugUdev = `
# This file contains udev rules for optical drives.
#
# Do not edit this file, it will be overwritten on updates

KERNEL=="sr[0-9]*", NAME="%%k", SYMLINK+="scd%%n", TAG+="%s"
`

// The type for optical interface
type opticalDriveInterface struct{}

// Getter for the name of the optical drive interface
func (iface *opticalDriveInterface) Name() string {
	return "optical-drive"
}

func (iface *opticalDriveInterface) MetaData() interfaces.MetaData {
	return interfaces.MetaData{
		Summary:              opticalDriveSummary,
		ImplicitOnCore:       true,
		ImplicitOnClassic:    true,
		BaseDeclarationSlots: opticalDriveBaseDeclarationSlots,
	}
}

func (iface *opticalDriveInterface) String() string {
	return iface.Name()
}

// Check validity of the defined slot
func (iface *opticalDriveInterface) SanitizeSlot(slot *interfaces.Slot) error {
	// Does it have right type?
	if iface.Name() != slot.Interface {
		panic(fmt.Sprintf("slot is not of interface %q", iface))
	}
	return nil
}

// Checks and possibly modifies a plug
func (iface *opticalDriveInterface) SanitizePlug(plug *interfaces.Plug) error {
	if iface.Name() != plug.Interface {
		panic(fmt.Sprintf("plug is not of interface %q", iface))
	}
	// Currently nothing is checked on the plug side
	return nil
}

func (iface *opticalDriveInterface) AppArmorConnectedPlug(spec *apparmor.Specification, plug *interfaces.Plug, plugAttrs map[string]interface{}, slot *interfaces.Slot, slotAttrs map[string]interface{}) error {
	spec.AddSnippet(opticalDriveConnectedPlugAppArmor)
	return nil
}

func (iface *opticalDriveInterface) UDevConnectedPlug(spec *udev.Specification, plug *interfaces.Plug, plugAttrs map[string]interface{}, slot *interfaces.Slot, slotAttrs map[string]interface{}) error {
	for appName := range plug.Apps {
		tag := udevSnapSecurityName(plug.Snap.Name(), appName)
		spec.AddSnippet(fmt.Sprintf(opticalDriveConnectedPlugUdev, tag))
	}
	return nil
}

func (iface *opticalDriveInterface) AutoConnect(*interfaces.Plug, *interfaces.Slot) bool {
	// Allow what is allowed in the declarations
	return true
}

func init() {
	registerIface(&opticalDriveInterface{})
}
