#!/bin/sh

set -eu

if [ -d /run/mnt/gadget/splash/plymouth/themes/vendor ]; then
  conf=vendor
elif [ -d /run/mnt/data/system-data ]; then
  conf=core
else
  conf=classic
fi

ln -sf "${conf}.conf" /etc/plymouth/plymouthd.conf
