#!/bin/sh -e

# Note: This snap is used for testing which requires this default-configure hook
# to be kept in sync with the configure hook

# Snapshot information
infoFile="$SNAP_COMMON"/default-configure-info
valueA=$( snapctl get a )
valueB=$( snapctl get b )
{
    echo "a: $valueA"
    echo "b: $valueB"
    echo "services:"
    snapctl services
} > "$infoFile"

# Append "a" to indicate default-configure hook modified it
snapctl set a="$valueA+defaultConfigureHook"
