#!/bin/sh -e

# Snapshot information
infoFile="$SNAP_COMMON"/default-configure-info
valueA=$( snapctl get a )
valueB=$( snapctl get b )
{
echo "a: $valueA" 
echo "b: $valueB"
echo "services:"
echo "<"
snapctl services
echo ">"
} > "$infoFile"

# Append "a" to indicate default-configure hook modified it
snapctl set a="$valueA+defaultConfigureHook"

# Indicate done
echo "default-configure-done: $( date +"%m %d %Y %H:%M:%S" )" >> "$infoFile"
