#!/bin/sh

KEY="some-random-key-value"
HASH="some-random-hash-value"

# Get the request-id that was set by snapd
REQUEST_ID=$(snapctl get registration.request-id)

# Set the registration body as a single JSON string (use single quotes to avoid shell interpretation)
snapctl set registration.body='"{\"hardware-id-key\": \"$KEY\", \"hardware-id-key-sha384\": \"$HASH\", \"request-id-signature\": \"$REQUEST_ID\"}"'