#! /bin/sh
# prerm script for snapd

set -e

echo "prerm called with $1"

if [ "$1" = "remove" -o "$1" = "upgrade" ]; then
    echo "prerm called with $1"
    if [ -d /run/systemd/system ]; then
        systemctl stop snapd.boot-ok.service
        systemctl stop snapd.refresh.timer
        systemctl stop snapd.refresh.service
        systemctl stop snapd.socket
        systemctl stop snapd.service
    fi
fi
