#!/usr/bin/expect -f

set timeout 20

spawn bash
send "ls /dev/pts\n"
expect "\[0-9]*ptmx" {} timeout { exit 1 }

# Launch app and checks contents of /dev/pts, should have only ptmx
spawn su -l -c "/snap/bin/test-snapd-tools.sh" test
expect "bash-4.3\\$" {} timeout { exit 1 }
send "ls /dev/pts\n"
expect {
    timeout { exit 1 }
    "\[0-9]" { exit 1 }
    "ptmx"
}

# From within confined app, open a pty
send "python3\n"
expect ">>>" {} timeout { exit 1 }
send "import os, pty, sys\n"
send "os.listdir('/dev/pts')\n"
expect "\['ptmx'\]" {} timeout { exit 1 }
send "pty.openpty()\n"
send "os.listdir('/dev/pts')\n"
expect "\['0', 'ptmx'\]" {} timeout { exit 1 }
send "sys.exit(0)\n"
expect "bash-4.3\\$" {} timeout { exit 1 }

# From with confined app, verify pty was closed (assumes that the last program
# closes it properly, which the above does)
send "ls /dev/pts\n"
expect {
    timeout { exit 1 }
    "\[0-9]" { exit 1 }
    "ptmx"
}
