// -*- Mode: Go; indent-tabs-mode: t -*-

/*
 * Copyright (C) 2017 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package patch

import (
	"os"

	"github.com/snapcore/snapd/dirs"
	"github.com/snapcore/snapd/overlord/state"
)

func init() {
	patches[7] = patch7
}

// patch7:
//  - remove all snap cookies from the state and the disk,
//    they will get regenerated by snapmanager.
func patch7(st *state.State) error {
	if err := os.RemoveAll(dirs.SnapCookieDir); err != nil {
		return err
	}

	snapCookies := make(map[string]string)
	st.Set("snap-cookies", &snapCookies)

	return nil
}
