#!/bin/sh

set -e

case "$1" in
    configure)
        # Create the private tmp directory for snap-confine
        install -d -m 0700 /tmp/snap-private-tmp

        # Ensure that the void directory has correct permissions.
        chmod 111 /var/lib/snapd/void

        # ensure required caps on snap-confine
        setcap -q - /usr/lib/snapd/snap-confine < /usr/lib/snapd/snap-confine.caps
        ;;
esac

#DEBHELPER#
