#!/bin/sh

# rsyslog.service is expected to be a symlink at this point, and apparmor
# doesn't control readlink, so this should work even without devmode or
# system-files plug.
RSYSLOG=$(readlink /etc/systemd/system/rsyslog.service)
echo "rsyslog symlink: $RSYSLOG" > "$SNAP_COMMON"/debug.txt || true

LOCALTIME=$(readlink /etc/writable/localtime)
echo "localtime symlink: $LOCALTIME"  >> "$SNAP_COMMON"/debug.txt  2>&1 || true
