#!/bin/sh

if snapctl is-connected network-manager; then
    dbus-send --system --dest=org.freedesktop.NetworkManager --type=method_call   --print-reply   /org/freedesktop/NetworkManager org.freedesktop.DBus.Introspectable.Introspect > "$SNAP_COMMON/introspect.txt"
else
    echo "network-manager not connected" > "$SNAP_COMMON/introspect.txt"
fi
