#!/bin/sh

if snapctl is-connected upower-observe; then
    # The dbus-send output starts with a variable header, tail filters it out.
    dbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.EnumerateDevices | tail --lines="+2" > "$SNAP_COMMON/enumerate.txt" 2>&1
else
    echo "upower-observe not connected" > "$SNAP_COMMON/enumerate.txt"
fi
