#!/bin/bash

set -xe

if nc -l 127.0.0.1 12345; then
    echo "should not be able to bind to anything"
fi

# this will fail if we can't run nc, which is allowed by the network interface
nc -h

snapctl set two-installed="${SNAP_COMPONENT_REVISION}"
