#!/bin/bash

set -xe

if nc -l 127.0.0.1 12345; then
    echo "should not be able to bind to anything"
fi

proxy_arg=
if [ -n "$HTTP_PROXY" ]; then
    proxy_arg="-x $HTTP_PROXY"
fi
# shellcheck disable=SC2086
nc -zv $proxy_arg snapcraft.io 80

echo "ran remove hook" > /tmp/two-remove-hook-executed
