#!/bin/bash

# create new files in the $SNAP_SAVE_DATA and a directory

# write a config file to the ubuntu-save partition
cat << EOF > $SNAP_SAVE_DATA/my-data.conf
# empty configuration file
EOF

# create a new folder and create a cert file there
mkdir $SNAP_SAVE_DATA/certs
cat << EOF > $SNAP_SAVE_DATA/certs/myorg.cert
# insert certificate
EOF
