#!/bin/sh

# rsyslog.service is expected to be a symlink at this point, and apparmor
# doesn't control readlink, so this should work even without devmode or
# system-files plug.
RSYSLOG=$(readlink /etc/systemd/system/rsyslog.service)
echo "rsyslog symlink: $RSYSLOG" > "$SNAP_COMMON"/debug.txt 2>&1 || true

BACKLIGHT=$(readlink /etc/systemd/system/systemd-backlight@.service)
echo "backlight symlink: $BACKLIGHT" >> "$SNAP_COMMON"/debug.txt 2>&1 || true
