#!/bin/bash

REGISTRY_NAME="local-registry"
REGISTRY_PORT="5000"

show_help() {
    echo "usage: docker-state setup-local-registry"
    echo "       docker-state add-local-image <image-name> <tar-file>"
    echo "       docker-state clean-local-registry"
}

setup_local_registry(){
    # wait until docker is ready
    retry -n 20 --wait 1 sh -c 'docker ps'

    # Start local registry if not running
    if [ "$(docker ps -q -f name=${REGISTRY_NAME})" == "" ]; then
        echo "Starting local Docker registry on port ${REGISTRY_PORT}..."
        docker run -d -p ${REGISTRY_PORT} --restart=always --name ${REGISTRY_NAME} registry:2
    else
        echo "Local registry already running."
    fi
}

add_local_image(){
    TAR_FILE="$2"

    echo "Loading image into Docker..."
    docker load -i "${TAR_FILE}"
}

clean_local_registry(){
    # Stop and remove registry container
    docker stop local-registry 2>/dev/null || true
    docker rm local-registry 2>/dev/null || true

    # Delete local registry images
    docker images | grep localhost:5000 | awk '{print $1":"$2}' | xargs -r docker rmi
}

main() {
    if [ $# -eq 0 ]; then
        show_help
        exit 0
    fi

    case "${1:-}" in
        -h|--help)
            show_help
            exit 0
            ;;
        setup-local-registry)
                shift
                setup_local_registry "$@"
            ;;
        add-local-image)
                shift
                add_local_image "$@"
            ;;
        clean-local-registry)
                shift
                clean_local_registry
            ;;
        *)
            echo "docker-state: unknown command $*" >&2
            exit 1
            ;;
    esac
}

main "$@"