#!/bin/bash

show_help() {
    echo "usage: fs-state mock-dir <--new> [dirname]"
    echo "       fs-state restore-dir [dirname]"
    echo "       fs-state mock-file <--new> [filename]"
    echo "       fs-state restore-file [filename]"
    echo "       fs-state start-monitor"
    echo "       fs-state check-monitor"
}

_mock_dir() {
    local dir="$1"
    if [ ! -d "$dir" ]; then
        echo "fs-state: created mock directory: $dir"
        mkdir -p "$dir"
    fi
    touch "$dir.fake"
}

mock_dir() {
    local new=0
    local dir
    while [ $# -gt 0 ]; do
        case "$1" in
            --new)
                new=1
                shift
                ;;
            *)
                dir=$1
                shift
                ;;
        esac
    done

    if [ -d "$dir" ]; then
        if [ "$new" = 1 ]; then
            mv "$dir" "$dir.back"
        else
            cp -rf "$dir" "$dir.back"
        fi
    fi
    _mock_dir "$dir"
}

restore_dir() {
    local dir="$1"

    if [ -e "$dir.fake" ]; then
        echo "fs-state: restoring mocked directory: $dir"
        rm -rf "$dir"
        rm -f "$dir.fake"
    else
        echo "fs-state: cannot restore non-mocked directory: $dir" >&2
        exit 1
    fi
    if [ -d "$dir.back" ]; then
        mv "$dir.back" "$dir"
    fi
}

_mock_file() {
    local file="$1"
    if [ ! -e "$file" ]; then
        echo "fs-state: creating file: $file"
        echo "The file is a mock file used by fs-state." > "$file"
    fi
    echo "The .fake file is a marker file used by fs-state." > "$file.fake"
}

mock_file() {
    local new=0
    local file
    while [ $# -gt 0 ]; do
        case "$1" in
            --new)
                new=1
                shift
                ;;
            *)
                file=$1
                shift
                ;;
        esac
    done

    if [ -e "$file" ]; then
        echo "fs-state: backing up original file: $file"
        if [ "$new" = 1 ]; then
            mv "$file" "$file.back"
        else
            cp -f "$file" "$file.back"
        fi
    fi
    # ensure the parent dir is available
    if [ ! -d "$(dirname "$file")" ]; then
        mkdir -p "$(dirname "$file")"
    fi
    _mock_file "$file"
}

restore_file() {
    local file="$1"
    if [ -e "$file.fake" ]; then
        echo "fs-state: restoring mocked file: $file"
        rm -f "$file"
        rm -f "$file.fake"
    else
        echo "fs-state: cannot restore non-mocked file: $file" >&2
        exit 1
    fi
    if [ -e "$file.back" ]; then
        mv "$file.back" "$file"
    fi
}

save_current_tree(){
    local dir=$1

    rm -rf "$dir"
    mkdir "$dir"
    # .snap files created in tests/lib/snaps are excluded as they are not deleted to be reused
    # runtime-state dir contains cursor and run log which are created during the first test
    tree -f /etc -I "*~" > "$dir"/etc
    tree -f /boot -I "*~" > "$dir"/boot
    tree -f /home -I "*~|$PROJECT_PATH/tests/lib/snaps/*/*.snap|$PROJECT_PATH/tests/runtime-state/*" > "$dir"/home
    tree -f /root -I "*~" > "$dir"/root
}

start_monitor() {
    save_current_tree /tmp/fs-initial
 }

check_monitor() {
    save_current_tree /tmp/fs-final
    
    rm -f /tmp/fs-diff
    # shellcheck disable=SC2045
    for f in $(ls /tmp/fs-initial); do
        diff /tmp/fs-initial/"$f" /tmp/fs-final/"$f" >> /tmp/fs-diff
    done

    if [ -z "$(find /tmp -empty -name fs-diff)" ]; then
        echo "the diff file is not empty:"
        cat /tmp/fs-diff 
        exit 1
    fi
}

main() {
    if [ $# -eq 0 ]; then
        show_help
        exit 0
    fi

    action=
    while [ $# -gt 0 ]; do
        case "$1" in
            -h|--help|'')
                show_help
                exit 0
                ;;
            *)
                action=$(echo "$1" | tr '-' '_')
                shift
                break
                ;;
        esac
    done

    "$action" "$@"
}

main "$@"
