#!/bin/bash
# Source spread-funcs.sh which, at runtime, contains the real definition of
# MATCH and execute it.

# shellcheck source=tests/lib/spread-funcs.sh
. "$TESTSLIB/spread-funcs.sh"

MATCH "$@"
