#!/bin/bash -e

show_help() {
    echo "usage: prepare"
    echo "       restore"
    echo "       build-image IMAGE-TYPE"
    echo "       boot-image IMAGE-TYPE [--param-cd PARAM] [--param-mem PARAM]"
    echo "       start-vm"
    echo "       shutdown-vm"
    echo "       delete-vm"
    echo ""
    echo "Available options:"
    echo "  -h --help   show this help message."
    echo ""
    echo "COMMANDS:"
    echo "  prepare:     creates all the directories needed to run a nested test"
    echo "  restore:     deletes all the directories and data used by nested tests"
    echo "  build-image: creates an image using ubuntu image tool"
    echo "  boot-image:  first boot of the image which it remains running"
    echo "  start-vm:    start the booted vm"
    echo "  shutdown-vm: shutdown the running vm"
    echo "  delete-vm:   delete the booten vm"
    echo ""
    echo "IMAGE-TYPES:"
    echo "  core: work with a core image"
    echo "  classic: work with a classic image"
    echo ""
}

prepare() {
    nested_prepare_env
}

restore() {
    nested_cleanup_env
}

build_image() {
    if [ $# -eq 0 ]; then
        show_help
        exit 1
    fi
    while [ $# -gt 0 ]; do
        case "$1" in
            classic)
                nested_create_classic_vm
                exit
                ;;
            core)
                nested_create_core_vm
                exit
                ;;
            *)
                echo "nested-state: unsupported parameter $1" >&2
                exit 1
                ;;
        esac
    done
}

boot_image() {
    if [ $# -eq 0 ]; then
        show_help
        exit 1
    fi
    local action=
    case "$1" in
        classic)
            shift 1
            action=nested_start_classic_vm
            ;;
        core)
            shift 1
            action=nested_start_core_vm
            ;;
        *)
            echo "nested-state: unsupported parameter $1" >&2
            exit 1
            ;;
    esac

    while [ $# -gt 0 ]; do
        case "$1" in
            --param-cd)
                export NESTED_PARAM_CD="$2"
                shift 2
                ;;
            --param-mem)
                export NESTED_PARAM_MEM="$2"
                shift 2
                ;;
            *)
                echo "nested-state: unsupported parameter $1" >&2
                exit 1
                ;;
        esac
    done

    "$action"
}


start_vm() {
    nested_start
}

shutdown_vm() {
    nested_shutdown
}

delete_vm() {
    nested_destroy_vm
}

main() {
    if [ $# -eq 0 ]; then
        show_help
        exit 0
    fi

    local subcommand="$1"
    local action=
    while [ $# -gt 0 ]; do
        case "$1" in
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                action=$(echo "$subcommand" | tr '-' '_')
                shift
                break
                ;;
        esac
    done

    if [ -z "$(declare -f "$action")" ]; then
        echo "nested-state: no such command: $subcommand"
        show_help
        exit 1
    fi

    #shellcheck source=tests/lib/nested.sh
    . "$TESTSLIB/nested.sh"
    "$action" "$@"
}

main "$@"
