#!/bin/bash

show_help() {
    echo "usage: network-state get-default-iface"
    echo "       network-state wait-listen-port <PORT>"
    echo "       network-state make-network-service <SERVICE_NAME> <PORT>"
}

get_default_iface(){
    ip route get 8.8.8.8 | awk '{ print $5; exit }'
}

wait_listen_port(){
    PORT="$1"

    for _ in $(seq 120); do
        if ss -lnt | grep -Pq "LISTEN.*?:$PORT +.*?\\n*"; then
            break
        fi
        sleep 0.5
    done

    # Ensure we really have the listen port, this will fail with an
    # exit code if the port is not available.
    ss -lnt | grep -Pq "LISTEN.*?:$PORT +.*?\\n*"
}

make_network_service() {
    SERVICE_NAME="$1"
    PORT="$2"

    systemd-run --unit "$SERVICE_NAME" sh -c "while true; do printf 'HTTP/1.1 200 OK\\n\\nok\\n' |  nc -l -p $PORT -w 1; done"
    wait_listen_port "$PORT"
}

main() {
    if [ $# -eq 0 ]; then
        show_help
        exit 0
    fi

    subcommand=$1
    action=
    while [ $# -gt 0 ]; do
        case "$1" in
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                action=$(echo "$subcommand" | tr '-' '_')
                shift
                break
                ;;
        esac
    done

    if [ -z "$(declare -f "$action")" ]; then
        echo "network-state: no such command $subcommand" >&2
        show_help
        exit 1
    fi

    "$action" "$@"
}

main "$@"