#!/bin/sh
# This script executes whatever is given as argument and inverts the return
# value. It is meant as a workaround for shellcheck discovery
# https://github.com/koalaman/shellcheck/wiki/SC2251 where shell scripts using
# "set -e" are not failing with a trivial code like "! true"
! "$@"
