#!/usr/bin/python3

import argparse
import hashlib
import sys

def parse_arguments():
    parser = argparse.ArgumentParser(description='calculate sha3-384 of stdin')
    return parser.parse_args()

def main():
    h = hashlib.sha3_384()
    while True:
        d = sys.stdin.buffer.read(4096)
        if len(d) == 0:
            break
        h.update(d)
    print(h.hexdigest())

if __name__ == '__main__':
    parse_arguments()
    main()
