#!/bin/sh

show_help() {
    echo "usage: to-one-line [string]"
}

to_one_line(){
    echo "$1" | tr '\r\n' ' ' | tr -s ' '
}

main() {
	if [ $# -eq 0 ]; then
	    show_help
	    exit
	fi
	case "${1:-}" in
		-h|--help)
			show_help
			exit 0
			;;
		*)
			to_one_line "$1"
			;;
	esac
}

main "$@"
