#!/bin/sh
set -e

version="$1"
command -v ubuntu-core-initramfs >/dev/null 2>&1 || exit 0

# avoid running multiple times
if [ -n "$DEB_MAINT_PARAMS" ]; then
	eval set -- "$DEB_MAINT_PARAMS"
	if [ -z "$1" ] || [ "$1" != "configure" ]; then
		exit 0
	fi
fi

# do not clobber pre-signed .efi
if [ -e /boot/kernel.efi-"$version" ]; then
    exit 0
fi

ubuntu-core-initramfs create-initrd --kernelver "$version"

case $(dpkg --print-architecture) in
    amd64|arm64)
	case $version in
	    *-azure-fde)
		# Currently nullboot doesn't seal cmdline, thus it must be baked in for azure
		ubuntu-core-initramfs create-efi --unsigned --kernelver "$version" --cmdline "snapd_recovery_mode=cloudimg-rootfs console=tty1 console=ttyS0 earlyprintk=ttyS0 panic=60"
		;;
	    *)
		ubuntu-core-initramfs create-efi --unsigned --kernelver "$version"
		;;
	esac
esac
