#!/bin/sh -e

for file in /run/auditd.pid /run/auditd.state /var/run/auditd.pid /var/run/auditd.state ; do
	orig=
	if [ -f "$file" ] ; then
		orig="$(mktemp)"
		cp --preserve=all "$file" "$orig"
	fi
	echo "wrote to $file" > "$file"
	result="$(cat "$file")"
	test "$result" = "wrote to $file"
	echo "$result"
	rm "$file"
	if [ -n "$orig" ] ; then
		mv "$orig" "$file"
	fi
done
