#!/bin/bash

# install the files the same way the specific device does this - note we don't
# create the directories since that requires extra permissions we don't have
# here, system-files only allows us access to the specific files

# add modprobe.d config
cat << EOF > /run/mnt/ubuntu-data/system-data/_writable_defaults/etc/modprobe.d/my-modprobe.conf
# configure modprobe here
EOF

# add modules-load.d config
cat << EOF > /run/mnt/ubuntu-data/system-data/_writable_defaults/etc/modules-load.d/my-modules-load.conf
# load modules here
EOF

# add a udev rule
cat << EOF > /run/mnt/ubuntu-data/system-data/_writable_defaults/etc/udev/rules.d/09-my-custom-udev.rules
# do udev rules things here
EOF
