#! /bin/sh -e
# Prepare the initramfs image for the tests.

current_boot_dir=$1
writable_percent=$2
tree_dir=$(pwd)
initrd_unpack_dir=$ADT_ARTIFACTS/initrd

cp ${current_boot_dir}/initrd.img /tmp/initrd.xz
cd /tmp/
unxz /tmp/initrd.xz
mkdir $initrd_unpack_dir || true
cd $initrd_unpack_dir
cpio -id < ../initrd
cp $tree_dir/scripts/resize-writable-test scripts/local-premount/
sed -i "s/writable_percent=.*/writable_percent=${writable_percent}/" scripts/local-premount/resize-writable-test
sed -i '1i /scripts/local-premount/resize-writable-test "$@"\n[ -e /conf/param.conf ] && . /conf/param.conf' scripts/local-premount/ORDER
find .|cpio -o -H newc|xz -c -7 --check=crc32 > initrd.img
sudo mv initrd.img $current_boot_dir
