name: snapd
type: snapd
summary: Daemon and tooling that enable snap packages
description: |
  Install, configure, refresh and remove snap packages. Snaps are
  'universal' packages that work across many different Linux systems,
  enabling secure distribution of the latest apps and utilities for
  cloud, servers, desktops and the internet of things.

  Start with 'snap list' to see installed snaps.
adopt-info: snapd
# build-base is needed here for snapcraft to build this snap as with "modern"
# snapcraft
build-base: core22
package-repositories:
  - type: apt
    ppa: snappy-dev/image
grade: stable
license: GPL-3.0
confinement: strict

# Nested objects such as ubuntu-core-tracks must not be validated by Snapcraft
# or review-tools; snapd validates them via snap pack. Passthrough
# only skips Snapcraft validation.
# TODO: allow snapd-info in the store/review-tools snap.yaml schema for
# the snapd snap.
# TODO: allow snapd-info in Snapcraft so passthrough is not needed.
#passthrough:
#  snapd-info:
#    # Example:
#    #   ubuntu-core-tracks:
#    #     "18":
#    #       latest: "18"
#    #       fips-updates: "18-fips"
#    #     "20":
#    #       latest: "20"
#    #       fips-updates: "20-fips"
#    # Empty until the first Ubuntu Core version is onboarded.
#    ubuntu-core-tracks: {}

# Note that this snap is unusual in that it has no "apps" section.
#
# It is started via re-exec on classic systems and via special
# handling in the core18 snap on Ubuntu Core Systems.
#
# Because snapd itself manages snaps it must currently run totally
# unconfined (even devmode is not enough).
#
# See the comments from jdstrand in
# https://forum.snapcraft.io/t/5547/10

# There is no explicit mechanism for passing parameters/configuration through
# snapcraft at snap build time, so instead the build process looks for (or
# creates) the following stamp files, which influence the build process:
#
# - test-build - created by the CI (or the in-repo test build script), indicates
#   a test build with version override to 1337.*
#
parts:
  dynamic-linker:
    plugin: nil
    build-packages:
      - gawk
      - bison
      - quilt
      - python3-pyelftools
      - xz-utils
    source: https://git.launchpad.net/ubuntu/+source/glibc
    source-branch: ubuntu/jammy-updates
    source-type: git
    <<:
      - &dynamic-linker
        build-environment:
          - to amd64:
              - DYNAMIC_LINKER: ld-linux-x86-64.so.2
          - to s390x:
              - DYNAMIC_LINKER: ld64.so.1
          - to arm64:
              - DYNAMIC_LINKER: ld-linux-aarch64.so.1
          - to armhf:
              - DYNAMIC_LINKER: ld-linux-armhf.so.3
          - to riscv64:
              - DYNAMIC_LINKER: ld-linux-riscv64-lp64d.so.1
          - to ppc64el:
              - DYNAMIC_LINKER: ld64.so.2
    override-pull: |
      craftctl default
      QUILT_PATCHES=debian/patches quilt push -a
      patch -p1 <"${CRAFT_PROJECT_DIR}/build-aux/snap/local/rename-dynamic-loader-variables.patch"

    override-build: |
      rm -rf build
      mkdir -p build
      cd build
      unset LDFLAGS
      unset CPPFLAGS
      export CFLAGS="-pipe -O2 -g"
      cat <<EOF >configparms
      libdir=/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      slibdir=/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      rtldir=/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      EOF
      "${CRAFT_PART_SRC_WORK}/configure" --prefix=/snap/snapd/current/usr
      make -j"${CRAFT_PARALLEL_BUILD_COUNT}" -C .. objdir="${PWD}" "${PWD}/linkobj/libc_pic.a"
      make elf/ldso_install DESTDIR="${CRAFT_PART_INSTALL}"
      "${CRAFT_PROJECT_DIR}/build-aux/snap/local/minidebuginfo" "${CRAFT_PART_INSTALL}/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}"
      install -Dm755 -t "${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}" "${CRAFT_PART_INSTALL}/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}"
    stage:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ld*.so*

  runtime:
    plugin: nil
    stage-packages:
      - libblkid1
      - libc6
      - libcap2
      - libexpat1
      - libgcc-s1
      - liblz4-1
      - liblzma5
      - liblzo2-2
      - libseccomp2
      - libudev1
      - libzstd1
      - xdelta3
      - zlib1g
      - on armhf:
        - libteec1
      - on arm64:
        - libteec1
    stage:
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ld*.so*
      - -lib32
      - -lib64
      - -usr/lib32
      - -usr/lib64
      - -etc/ld.so.conf.d
      - -usr/share/man
      - -usr/share/lintian
      - -usr/share/lintian/**
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libnss_*.so.2
    override-build: |
      craftctl default
      cp -avT "${CRAFT_PART_INSTALL}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}" "${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}"
      rm -rf "${CRAFT_PART_INSTALL}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}"
      rm -f "${CRAFT_PART_INSTALL}/lib/${DYNAMIC_LINKER}"
      find "${CRAFT_PART_INSTALL}/usr/share/doc" \( -not -type d -not -name "copyright" -delete \) -o \( -type d -empty -delete \)
    <<:
      - *dynamic-linker
    # FIXME: uncomment when https://bugs.launchpad.net/snapcraft/+bug/2097440 is fixed
    # override-prime: |
    #   craftctl default
    #   python3 "${CRAFT_PROJECT_DIR}/build-aux/snap/local/patch-dl.py" "/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}"

  # FIXME: remove when https://bugs.launchpad.net/snapcraft/+bug/2097440 is fixed
  prime-runtime:
    plugin: nil
    after:
      - runtime
    <<:
      - *dynamic-linker
    override-prime: |
      craftctl default
      CRAFT_PART_INSTALL="${CRAFT_PART_INSTALL}/../../runtime/install" \
        python3 "${CRAFT_PROJECT_DIR}/build-aux/snap/local/patch-dl.py" "/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}"

  apparmor:
    plugin: autotools
    build-packages:
      - autoconf-archive
      - bison
      - flex
      - gettext
      - g++
      - pkg-config
      - wget
      - libzstd-dev
    source: https://gitlab.com/apparmor/apparmor/-/archive/v5.0.2/apparmor-v5.0.2.tar.gz
    source-checksum: sha256/bef45f228c0bde2f80d9630084e56bd8020b3fc4dfa7ee48a6aca585bb5ea0ed
    override-build: |
      # For some reason, some snapcraft version remove the "build-aux" folder
      # and move the contents up when the data is uploaded; this conditional
      # manages it.
      LOCAL_APPARMOR_DIR="${CRAFT_PROJECT_DIR}"/build-aux/snap/local/apparmor/
      if [ ! -d $LOCAL_APPARMOR_DIR ]; then
        LOCAL_APPARMOR_DIR="${CRAFT_PROJECT_DIR}"/snap/local/apparmor/
      fi

      cd "${CRAFT_PART_BUILD}"/libraries/libapparmor
      ./autogen.sh
      ./configure --prefix=/usr --libdir="/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}" --disable-man-pages --disable-perl --disable-python --disable-ruby --disable-shared
      make -j"${CRAFT_PARALLEL_BUILD_COUNT}"
      make -C src install DESTDIR="${CRAFT_PART_INSTALL}"
      make -C include install DESTDIR="${CRAFT_PART_INSTALL}"
      cd ${CRAFT_PART_BUILD}/parser
      # copy in a pregenerated list of network address families so that the
      # parser gets built to support as many as possible even if glibc in
      # the current build environment does not support them
      cp -a "${LOCAL_APPARMOR_DIR}"/af_names.h .
      make -j"${CRAFT_PARALLEL_BUILD_COUNT}" WITH_STATIC_LINKING=1
      install -Dm755 -s -t "${CRAFT_PART_INSTALL}/usr/lib/snapd" apparmor_parser
      install -Dm644 -t "${CRAFT_PART_INSTALL}/usr/lib/snapd/apparmor" parser.conf
      cd "${CRAFT_PART_BUILD}/profiles"
      make -j"${CRAFT_PARALLEL_BUILD_COUNT}"
      mkdir -p "${CRAFT_PART_INSTALL}/usr/lib/snapd/apparmor.d"
      cp -a apparmor.d/abi "${CRAFT_PART_INSTALL}/usr/lib/snapd/apparmor.d"
      cp -a apparmor.d/abstractions "${CRAFT_PART_INSTALL}/usr/lib/snapd/apparmor.d"
      cp -a apparmor.d/tunables "${CRAFT_PART_INSTALL}/usr/lib/snapd/apparmor.d"
    prime:
      # We are statically linked
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/**
      - -usr/include
    <<:
      - *dynamic-linker
    override-prime: |
      craftctl default
      python3 "${CRAFT_PROJECT_DIR}/build-aux/snap/local/patch-dl.py" "/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}"

  patchelf:
    plugin: autotools
    build-packages:
      - autoconf-archive
    # as of 0.18.0-1.1build1 in Oracular, here are no relevant patches to apply
    source: http://archive.ubuntu.com/ubuntu/pool/universe/p/patchelf/patchelf_0.18.0.orig.tar.gz
    source-checksum: sha256/1451d01ee3a21100340aed867d0b799f46f0b1749680028d38c3f5d0128fb8a7
    # nothing to prime
    prime: [-*]

  snapd:
    plugin: meson
    source: .
    meson-parameters:
      - "--buildtype=debugoptimized"
      - "-Db_pie=true"
      - "-Dprefix=/usr"
      - "-Dlibexecdir=lib/snapd"
      - "-Dcore=true"
      - "-Dsecboot=true"
      - "-Dusergo=true"
      - "--auto-features=enabled"
      - "-Ddracut=disabled"
      - "-Dunit-tests=disabled"
      - "-Dvendored=disabled"
      - "-Dstatic-checks=false"
      - "-Dlibselinux=disabled"
      - "-Dselinux=disabled"
      - "-Dset-perms=true"
      - "-Dsetcap=true"
      - "--native-file=config.ini"
    build-snaps:
      - go/1.24/stable # the default Go toolchain
    after:
      - apparmor
      - patchelf
    build-packages:
      - meson
      - git
      - dpkg-dev
      - xfslibs-dev
      - libblkid-dev
      - libudev-dev
      - libcap-dev
      - libseccomp-dev
      - libdbus-1-dev
      - pkg-config
      - python3-docutils
      - libcap2-bin
      - on armhf:
        - optee-client-dev
      - on arm64:
        - optee-client-dev
      - xz-utils
    override-pull: |
      craftctl default
      ln -sfn packaging/ubuntu-16.04 debian
      # set version, this needs dpkg-parsechangelog (from dpkg-dev) and git
      VERSION="$(./mkversion.sh --output-only)"

      if [ -f test-build ]; then
          VERSION="1337.${VERSION}"
      fi

      craftctl set version="$VERSION"
    override-build: |
      if [ -f "${CRAFT_PART_SRC}/test-build" ]; then
        test_keys=true
      else
        test_keys=false
      fi

      case "${CRAFT_ARCH_BUILD_FOR}" in
        arm64|armhf)
          optee=true
          ;;
        amd64)
          nvidia_multiarch=true
          host_arch_32bit_triplet=i386-linux-gnu
          ;;
      esac

      cat <<EOF >config.ini
      [project options]
      test-keys = ${test_keys}
      nvidia-multiarch = ${nvidia_multiarch-false}
      host-arch-triplet = '${CRAFT_ARCH_TRIPLET_BUILD_FOR}'
      host-arch-32bit-triplet = '${host_arch_32bit_triplet-unset}'
      optee = ${optee-false}
      goldflags = '-L/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}'
      EOF

      craftctl default

      install -Dm644 "${CRAFT_PART_SRC}/data/preseed.json" "${CRAFT_PART_INSTALL}/usr/lib/snapd/preseed.json"

      # TODO: For now snapd expects a renamed apparmor profile to
      # work-around LP#1673247. We should fix that since the snapd
      # should not need that work-around.
      mv "${CRAFT_PART_INSTALL}/etc/apparmor.d/usr.lib.snapd.snap-confine" "${CRAFT_PART_INSTALL}/etc/apparmor.d/usr.lib.snapd.snap-confine.real"

      # copy helper for collecting debug output
      cp -av "${CRAFT_PART_SRC}/debug-tools/snap-debug-info.sh" ${CRAFT_PART_INSTALL}/usr/lib/snapd/

      if env -C "${CRAFT_PART_SRC}" sh -x "mkversion.sh" --output-only | grep "dirty"; then
        mkdir -p "${CRAFT_PART_INSTALL}/usr/lib/snapd"
        (
          echo "dirty git tree during build detected:"
          git -C "${CRAFT_PART_SRC}" status
          git -C "${CRAFT_PART_SRC}" diff
        ) > "${CRAFT_PART_INSTALL}/usr/lib/snapd/dirty-git-tree-info.txt"
      fi

      find "${CRAFT_PART_INSTALL}/usr/lib/snapd" "${CRAFT_PART_INSTALL}/usr/bin" -type f -exec "${CRAFT_PROJECT_DIR}/build-aux/snap/local/minidebuginfo" {} ";"

      # minidebuginfo resets capabilities
      setcap -q - "${CRAFT_PART_INSTALL}/usr/lib/snapd/snap-confine" \
           < "${CRAFT_PART_INSTALL}/usr/lib/snapd/snap-confine.caps"
      getcap "${CRAFT_PART_INSTALL}/usr/lib/snapd/snap-confine"
    <<:
      - *dynamic-linker
    override-prime: |
      craftctl default
      # use patchelf built in earlier step
      PATH="${CRAFT_STAGE}"/usr/local/bin:$PATH \
          "${CRAFT_PROJECT_DIR}/build-aux/snap/local/patch-dl.py" \
              "/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}"

      # verify file capabilities
      caps="$(getcap "${CRAFT_PART_INSTALL}/usr/lib/snapd/snap-confine" | awk '{print $2}')"
      expected_caps="$(cat "${CRAFT_PART_INSTALL}/usr/lib/snapd/snap-confine.caps")"
      echo "-- expecting caps: $expected_caps"
      echo "-- actual caps:    $caps"
      test "$caps" = "$expected_caps"

  check-linker:
    plugin: nil
    build-packages:
      - patchelf
    after:
      # Must run after everything else
      - snapd
      - runtime
      - prime-runtime
      - apparmor
      - dynamic-linker
    <<:
      - *dynamic-linker
    override-prime: |
      craftctl default
      "${CRAFT_PROJECT_DIR}/build-aux/snap/local/verify-dl.py" \
          "/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}"

  # TODO This is needed due to an unsquashfs crash on big pseudo-files in older
  # squashfs-tools. Revert to pulling the deb when snapd is moved to the core26
  # base.
  squashfs-tools:
    plugin: make
    after:
      - dynamic-linker
    <<:
      - *dynamic-linker
    source: https://github.com/plougher/squashfs-tools.git
    source-type: git
    source-tag: "4.7.4"
    override-build: |
      cd squashfs-tools
      make -j${CRAFT_PARALLEL_BUILD_COUNT}
      install -Dm755 --strip --target-directory="${CRAFT_PART_INSTALL}/usr/bin" "${CRAFT_PART_BUILD}/squashfs-tools/mksquashfs"
      install -Dm755 --strip --target-directory="${CRAFT_PART_INSTALL}/usr/bin" "${CRAFT_PART_BUILD}/squashfs-tools/unsquashfs"
    override-prime: |
      craftctl default
      python3 "${CRAFT_PROJECT_DIR}/build-aux/snap/local/patch-dl.py" "/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}"
    build-packages:
      - liblz4-dev
      - liblzma-dev
      - liblzo2-dev
      - libzstd-dev
      - zlib1g-dev
