name: snapd
type: snapd
summary: Daemon and tooling that enable snap packages
description: |
  Install, configure, refresh and remove snap packages. Snaps are
  'universal' packages that work across many different Linux systems,
  enabling secure distribution of the latest apps and utilities for
  cloud, servers, desktops and the internet of things.

  Start with 'snap list' to see installed snaps.
adopt-info: snapd
# build-base is needed here for snapcraft to build this snap as with "modern"
# snapcraft
build-base: core22
package-repositories:
  - type: apt
    ppa: snappy-dev/image
grade: stable
license: GPL-3.0
confinement: strict

# Note that this snap is unusual in that it has no "apps" section.
#
# It is started via re-exec on classic systems and via special
# handling in the core18 snap on Ubuntu Core Systems.
#
# Because snapd itself manages snaps it must currently run totally
# unconfined (even devmode is not enough).
#
# See the comments from jdstrand in
# https://forum.snapcraft.io/t/5547/10

parts:
  dynamic-linker:
    plugin: nil
    build-packages:
      - gawk
      - bison
    source: https://git.launchpad.net/ubuntu/+source/glibc
    source-branch: ubuntu/jammy-updates
    source-type: git
    <<:
      - &dynamic-linker
        build-environment:
          - to amd64:
              - DYNAMIC_LINKER: ld-linux-x86-64.so.2
          - to s390x:
              - DYNAMIC_LINKER: ld64.so.1
          - to arm64:
              - DYNAMIC_LINKER: ld-linux-aarch64.so.1
          - to armhf:
              - DYNAMIC_LINKER: ld-linux-armhf.so.3
          - to riscv64:
              - DYNAMIC_LINKER: ld-linux-riscv64-lp64d.so.1
          - to ppc64el:
              - DYNAMIC_LINKER: ld64.so.2
    override-build: |
      rm -rf build
      mkdir -p build
      cd build
      unset LDFLAGS
      unset CPPFLAGS
      export CFLAGS="-pipe -O2 -g"
      cat <<EOF >configparms
      libdir=/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      slibdir=/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      rtldir=/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      EOF
      "${CRAFT_PART_SRC_WORK}/configure" --prefix=/snap/snapd/current/usr
      make -j"${CRAFT_PARALLEL_BUILD_COUNT}" -C .. objdir="${PWD}" "${PWD}/linkobj/libc_pic.a"
      make elf/ldso_install DESTDIR="${CRAFT_PART_INSTALL}"
      strip "${CRAFT_PART_INSTALL}/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}"
      install -Dm755 -t "${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}" "${CRAFT_PART_INSTALL}/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}"
    stage:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ld*.so*

  runtime:
    plugin: nil
    stage-packages:
      - libbrotli1
      - libc6
      - libcap2
      - libexpat1
      - libfreetype6
      - libgcc-s1
      - liblz4-1
      - liblzma5
      - liblzo2-2
      - libpng16-16
      - libseccomp2
      - libudev1
      - libzstd1
      - squashfs-tools
      - xdelta3
      - zlib1g
      # This is needed for using os/user on Ubuntu Core
      # TODO: do not use os/user, but io.systemd.NameServiceSwitch through dbus
      - libnss-extrausers
    stage:
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ld*.so*
      - -lib32
      - -lib64
      - -usr/lib32
      - -usr/lib64
      - -etc/ld.so.conf.d
      - -usr/share/man
      - -usr/share/lintian
      - -usr/share/lintian/**
    override-build: |
      craftctl default
      mv "${CRAFT_PART_INSTALL}/usr/lib/libnss_extrausers.so.2" "${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/"
      cp -rT "${CRAFT_PART_INSTALL}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}" "${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}"
      rm -rf "${CRAFT_PART_INSTALL}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}"
      find "${CRAFT_PART_INSTALL}/usr/share/doc" \( -not -type d -not -name "copyright" -delete \) -o \( -type d -empty -delete \)

  apparmor:
    plugin: autotools
    build-packages:
      - bison
      - flex
      - gettext
      - g++
      - pkg-config
      - wget
    source: https://launchpad.net/apparmor/3.0/3.0.8/+download/apparmor-3.0.8.tar.gz
    override-pull: |
      craftctl default
      # add support for mediating posix mqueue's and userns - these come from
      # the ubuntu source package for lunar
      # https://git.launchpad.net/ubuntu/+source/apparmor/tree/debian/patches/ubuntu?h=ubuntu/lunar
      for feature in mqueue userns; do
        wget https://git.launchpad.net/ubuntu/+source/apparmor/plain/debian/patches/ubuntu/add-${feature}-support.patch?h=ubuntu/lunar -O - | patch -p1
      done
      # apply local apparmor patches
      for patch in "${CRAFT_PROJECT_DIR}"/build-aux/snap/local/patches/apparmor/*; do
          patch -p1 < $patch
      done
    override-build: |
      cd "${CRAFT_PART_BUILD}"/libraries/libapparmor
      ./autogen.sh
      ./configure --prefix=/usr --libdir="/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}" --disable-man-pages --disable-perl --disable-python --disable-ruby
      make -j"${CRAFT_PARALLEL_BUILD_COUNT}"
      make -C src install DESTDIR="${CRAFT_PART_INSTALL}"
      make -C include install DESTDIR="${CRAFT_PART_INSTALL}"
      cd ${CRAFT_PART_BUILD}/parser
      # copy in a pregenerated list of network address families so that the
      # parser gets built to support as many as possible even if glibc in
      # the current build environment does not support them
      # For some reason, some snapcraft version remove the "build-aux" folder
      # and move the contents up when the data is uploaded; this conditional
      # manages it.
      if [ -d "${CRAFT_PROJECT_DIR}/build-aux" ]; then
        cp "${CRAFT_PROJECT_DIR}"/build-aux/snap/local/apparmor/af_names.h .
      else
        cp "${CRAFT_PROJECT_DIR}"/snap/local/apparmor/af_names.h .
      fi
      make -j"${CRAFT_PARALLEL_BUILD_COUNT}"
      install -Dm755 -t "${CRAFT_PART_INSTALL}/usr/lib/snapd" apparmor_parser
      install -Dm644 -t "${CRAFT_PART_INSTALL}/usr/lib/snapd/apparmor" parser.conf
      cd "${CRAFT_PART_BUILD}/profiles"
      make -j"${CRAFT_PARALLEL_BUILD_COUNT}"
      mkdir -p "${CRAFT_PART_INSTALL}/usr/lib/snapd/apparmor.d"
      cp -a apparmor.d/abi "${CRAFT_PART_INSTALL}/usr/lib/snapd/apparmor.d"
      cp -a apparmor.d/abstractions "${CRAFT_PART_INSTALL}/usr/lib/snapd/apparmor.d"
      cp -a apparmor.d/tunables "${CRAFT_PART_INSTALL}/usr/lib/snapd/apparmor.d"
    prime:
      # We are statically linked
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/**
      - -usr/include

  snapd:
    plugin: nil
    source: .
    build-snaps:
      - go/1.18/stable
    after:
      - apparmor
    # these packages are needed to call mkversion.sh in override-pull, all other
    # dependencies are installed using apt-get build-dep
    build-packages:
      - git
      - dpkg-dev
      - autoconf
      - autoconf-archive
      - automake
      - xfslibs-dev
      - libudev-dev
      - libcap-dev
      - libseccomp-dev
      - pkg-config
    override-pull: |
      craftctl default
      # set version, this needs dpkg-parsechangelog (from dpkg-dev) and git
      craftctl set version="$(./mkversion.sh --output-only)"
      ./get-deps.sh --skip-unused-check
    override-build: |
      ./mkversion.sh
      cd "${CRAFT_PART_BUILD}/cmd"

      autoreconf -fvi
      ./configure --prefix=/usr --libexec=/usr/lib/snapd --without-unit-tests --enable-static-libapparmor --disable-host-binaries
      make -j"${CRAFT_PARALLEL_BUILD_COUNT}"
      make -j1 DESTDIR="${CRAFT_PART_INSTALL}" install

      cd "${CRAFT_PART_BUILD}"

      # Work-around for snapcraft not working with git worktrees
      # We detect it with .git being a file rather than a directory
      if [ -f .git ]; then
        EXTRA_GO_FLAGS="-buildvcs=false"
      fi
      CMDS=(bin/snap
            lib/snapd/snapd
            lib/snapd/snap-exec
            lib/snapd/snap-failure
            lib/snapd/snap-fde-keymgr
            lib/snapd/snap-preseed
            lib/snapd/snap-recovery-chooser
            lib/snapd/snap-repair
            lib/snapd/snap-seccomp
            lib/snapd/snap-update-ns
            lib/snapd/snapctl
            lib/snapd/snapd-apparmor)
      for cmd in "${CMDS[@]}"; do
        case "${cmd}" in
           # FIXME: some binaries need to be run confined in apps. But
           # instead we should allow apps to access dynamic linkers
           # and libraries from snapd.
           lib/snapd/snap-exec|lib/snapd/snapctl)
             export CGO_ENABLED=0
             GO_LD_FLAGS=()
             ;;
           lib/snapd/snap-update-ns)
             export CGO_ENABLED=1
             GO_LD_FLAGS=(--ldflags '-extldflags "-static"')
             ;;
           *)
             export CGO_ENABLED=1
             GO_LD_FLAGS=()
             ;;
        esac
        go build -mod=vendor "${GO_LD_FLAGS[@]}" ${EXTRA_GO_FLAGS-} -o "${CRAFT_PART_INSTALL}/usr/${cmd}" "github.com/snapcore/snapd/cmd/$(basename ${cmd})"
        unset CGO_ENABLED
      done

      make -C data -j"${CRAFT_PARALLEL_BUILD_COUNT}" all
      # wrappers/core18.go expects units in fixed paths so even when
      # systemd package will those, they have to continue to match our
      # paths. We force the value here in case we change the default.
      make -C data install DESTDIR="${CRAFT_PART_INSTALL}" SYSTEMDUSERUNITDIR=/usr/lib/systemd/user SYSTEMDSYSTEMUNITDIR=/lib/systemd/system
      # UC depends on this name (symlink)
      mv "${CRAFT_PART_INSTALL}/etc/profile.d/snapd.sh" "${CRAFT_PART_INSTALL}/etc/profile.d/apps-bin-path.sh"

      install -Dm644 data/info "${CRAFT_PART_INSTALL}/usr/lib/snapd/info"
      install -Dm644 data/preseed.json "${CRAFT_PART_INSTALL}/usr/lib/snapd/preseed.json"

      if sh -x ./mkversion.sh --output-only | grep "dirty"; then
        mkdir -p "${CRAFT_PART_INSTALL}/usr/lib/snapd"
        (
          echo "dirty git tree during build detected:"
          git status
          git diff
        ) > "${CRAFT_PART_INSTALL}/usr/lib/snapd/dirty-git-tree-info.txt"
      fi

      find "${CRAFT_PART_INSTALL}/usr/lib/snapd" "${CRAFT_PART_INSTALL}/usr/bin" -type f -exec strip {} ";"

  fix-linker:
    plugin: nil
    build-packages:
      - patchelf
      - python3-pyelftools
    after:
      # Must run after everything else
      - snapd
      - runtime
      - apparmor
      - dynamic-linker
    <<:
      - *dynamic-linker
    override-prime: |
      find "${CRAFT_PRIME}" -type f -exec python3 "${CRAFT_PROJECT_DIR}/build-aux/snap/local/is-exec.py" {} ";" -print -exec patchelf --set-interpreter "/snap/snapd/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/${DYNAMIC_LINKER}" {} ";"
      chmod u+s "${CRAFT_PRIME}"/usr/lib/snapd/snap-confine
