#!/usr/bin/python3

import os.path
import sys
import yaml

PKGNAME="basic-config"
CFG_FILE = os.path.join(os.environ["SNAP_DATA"], "cfg")

def get_config():
   config = {"config": {
               PKGNAME: {},
               }
            }
   if not os.path.exists(CFG_FILE):
      return config
   with open(CFG_FILE) as fp:
      val = fp.read()
   config["config"]["basic-config"]["key"] = val
   return config


def set_config():
   config = yaml.load(sys.stdin)
   if not config:
      return

   val = config.get("key", "")
   if val:
      with open(CFG_FILE, "w") as fp:
         fp.write(val)


if __name__ == "__main__":
   set_config()
   config = get_config()
   yaml.dump(config, stream=sys.stdout, default_flow_style=False)
