#!/usr/bin/python3
# This wrapper is put in $PATH, ahead of the real "go" tool to work around
# some, er, curious, choices done by the Debian packaging helper scripts that
# pass verbose flag to "go generate" which in turns prints every single file in
# the source tree on a separate line. This easily dominates the build log,
# possibly exceeding the 4MB mark that travis chooses to keep by default.

# The real go is passed as an environment variable SNAPD_VANILLA_GO.

import sys 
import os

if __name__ == "__main__":
    go = os.getenv("SNAPD_VANILLA_GO")
    args = [arg for arg in sys.argv if arg != "-v"]
    os.execl(go, *args)
