#!/bin/sh
# gen-version.sh - generate snapd version files for a given version.
#
# This script writes the three version-bearing files that downstream
# distribution packaging needs in order to build snapd without invoking
# mkversion.sh:
#
#   - snapdtool/version_generated.go  UpstreamVersion = <version>,
#                                     DownstreamVersionSuffix = ""
#   - cmd/VERSION                     used by autotools (AC_INIT) for snap-confine
#   - data/info                       VERSION, SNAPD_APPARMOR_REEXEC and the
#                                     assertion formats map
#
# It is primarily used by packaging/pack-source when producing release source
# tarballs, so that the tarball carries the upstream version and downstream
# packaging only needs to provide DownstreamVersionSuffix (via a linker flag,
# see packaging/snapd.mk). It intentionally does NOT consult git or the Debian
# changelog; the version must be provided explicitly.
#
# usage: gen-version.sh <version> [srcdir]
set -e

version="$1"
srcdir="${2:-.}"

if [ -z "$version" ]; then
    echo "error: version is unset" >&2
    echo "usage: $(basename "$0") <version> [srcdir]" >&2
    exit 1
fi

if [ ! -d "$srcdir/snapdtool" ]; then
    echo "error: $srcdir does not look like the top of a snapd source tree" >&2
    exit 1
fi

# Only UpstreamVersion is baked in here. DownstreamVersionSuffix must NOT be
# assigned: it defaults to "" in snapdtool/version.go and is overridden at link
# time by distribution packaging (see packaging/snapd.mk). Assigning it in this
# init() would run after the linker and clobber the -X linker flag.
cat <<EOF > "$srcdir/snapdtool/version_generated.go"
package snapdtool

// generated by packaging/gen-version.sh; do not edit

func init() {
	UpstreamVersion = "$version"
}
EOF

cat <<EOF > "$srcdir/cmd/VERSION"
$version
EOF

# data/info carries the version plus the assertion formats map. Computing the
# formats requires running Go code, preferring the vendored dependencies when
# present.
MOD=-mod=vendor
if [ "$GO111MODULE" = "off" ]; then
    MOD=--
elif [ ! -d "$srcdir/vendor/github.com" ]; then
    MOD=--
fi
fmts=$(cd "$srcdir" && go run $MOD ./asserts/info)

cat <<EOF > "$srcdir/data/info"
VERSION=$version
SNAPD_APPARMOR_REEXEC=1
${fmts}
EOF

echo "*** Setting version to '$version'." >&2
