#!/bin/bash

set -e

show_help() {
    echo "usage: $(basename "$0") [-v <version>] [-o <output-dir>] [-g] [-h]"
    echo "       -v <version>       set version"
    echo "       -o <output-dir>    write source packages to this directory"
    echo "       -g                 use 'git describe' output as version string"
    echo "       -s                 use single source archive instead of no-vendor and"
    echo "                          only-vendor packages"
    echo "       -h                 show help"
    exit 1
}

if [ ! -e "packaging/$(basename "$0")" ]; then
    echo "must be executed at the top of srcdir"
    exit 1
fi

outdir=.
single=0

while getopts "v:o:gsh" arg; do
    case "$arg" in
        o)
            outdir="$OPTARG"
            ;;
        v)
            version="$OPTARG"
            ;;
        g)
            version="$(git describe | tr '-' '.')"
            ;;
        s)
            single=1
            ;;
        h|*)
            show_help
            ;;
    esac
done

if [ -z "$version" ]; then
    echo "error: version is unset"
    exit 1
fi

set -x

# Bake the upstream version into the source tree so that downstream
# distribution packaging does not need to invoke mkversion.sh. The generated
# files (snapdtool/version_generated.go, cmd/VERSION and data/info) are
# included in the tarball below and removed from the working tree afterwards
# to avoid leaving the tree dirty. Downstream packaging only needs to set
# DownstreamVersionSuffix (via a linker flag, see packaging/snapd.mk).
#
# Note: gen-version.sh computes the assertion formats in data/info by running
# `go run ./asserts/info`, so pack-source now requires a Go toolchain. This is
# always available in the release workflow (ci-github-release.yml installs Go)
# and in the CI packaging builds; keep this in mind when running pack-source on
# a minimal host.
version_files="snapdtool/version_generated.go cmd/VERSION data/info"
tmpdir=$(mktemp -d)
cleanup() {
    rm -rf "$tmpdir"
    rm -f $version_files
}
trap cleanup EXIT
./packaging/gen-version.sh "$version" .

if [[ "$single" == 0 ]]; then
    tar -cJf "$tmpdir"/snapd_"$version".no-vendor.tar.xz \
        --exclude='./vendor/*' \
        --exclude='./c-vendor/squashfuse' \
        --exclude='.git' --exclude='.git/*' \
        --exclude='.image-garden/*' \
        --exclude='./packaging/*/.build/*' \
        --exclude='./built-snap/*' \
        --exclude='./*.snap' \
        --transform "s#^#snapd-$version/#" .
    tar -cJf "$tmpdir"/snapd_"$version".only-vendor.tar.xz \
        --exclude='.git' --exclude='.git/*' \
        --exclude='.image-garden/*' \
        --exclude='./packaging/*/.build/*' \
        --exclude='./built-snap/*' \
        --exclude='./*.snap' \
        --transform "s#^#snapd-$version/#" vendor c-vendor

    mv "$tmpdir"/snapd_"$version".no-vendor.tar.xz "$outdir"/
    mv "$tmpdir"/snapd_"$version".only-vendor.tar.xz "$outdir"/
else
    tar -cJf "$tmpdir"/snapd_"$version".vendor.tar.xz \
        --exclude='.git' --exclude='.git/*' \
        --exclude='.image-garden/*' \
        --exclude='./packaging/*/.build/*' \
        --exclude='./built-snap/*' \
        --exclude='./*.snap' \
        --transform "s#^#snapd-$version/#" .
    mv "$tmpdir"/snapd_"$version".vendor.tar.xz "$outdir"/
fi
