#!/usr/bin/env python3

import dbus
import os
import sys


def _get_obj():
    return dbus.SystemBus().get_object("com.ubuntu.location.Service", "/com/ubuntu/location/Service")


def get():
    obj = _get_obj()
    print(obj.Get(dbus_interface="com.ubuntu.location.Service"))


def set():
    obj = _get_obj()
    print(obj.Set(dbus_interface="com.ubuntu.location.Service"))


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "Set":
        sys.exit(set())
    else:
        sys.exit(get())
