#!/bin/sh

echo "Getting attributes from confirm-plug-foo hook"

if ! output=$(snapctl iget read); then
    echo "Expected snapctl iget to be able to read the value of 'read' attribute"
    exit 1
fi

PATTERN="read.:\s*\[\s*\n\
\s*\"/etc\",\n\
\s*\"/usr\"\n\
\s*\]\n\
\}"

echo "$output" | grep -Pzq "$PATTERN"

if ! output=$(snapctl iget target); then
    echo "Expected snapctl iget to be able to read the value of 'target' attribute"
    exit 1
fi

expected_output="slottarget"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

if snapctl iset target=slottarget; then
    echo "Expected snapctl iset to fail when run from confirm-plug hook"
    exit 1
fi
