#!/bin/sh

echo "Setting and getting attribute value from prepare-plug-foo hook"

# Set own 'target' attribute.
if ! snapctl set :foo target=plugtarget; then
    echo "Expected snapctl set to be able to set the value of 'target' attribute"
    exit 1
fi

# Read own (plug's) 'target' attribute
if ! output=$(snapctl get --plug :foo target); then
    echo "Expected snapctl get to be able to read the value of 'target' attribute"
    exit 1
fi

expected_output="plugtarget"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi
