#!/bin/sh

echo "Setting and getting attribute value from prepare-plug-foo hook"

# Read the value of static 'target' attribute
if ! output=$(snapctl get :foo target); then
    echo "Expected snapctl get to be able to read the value of own 'target' attribute"
    exit 1
fi
expected_output="initialtarget"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi

# Set a dynamic attribute.
if ! snapctl set :foo newplugattribute=xyz; then
    echo "Expected snapctl set to be able to set the value of own 'target' attribute"
    exit 1
fi

# Read dynamic attribute
if ! output=$(snapctl get :foo newplugattribute); then
    echo "Expected snapctl get to be able to read the value of own dynamic attribute"
    exit 1
fi
expected_output="xyz"
if [ "$output" != "$expected_output" ]; then
    echo "Expected output to be '$expected_output', but it was '$output'"
    exit 1
fi
