// -*- Mode: Go; indent-tabs-mode: t -*-

/*
 * Copyright (C) 2026 Canonical Ltd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package cli

import (
	"context"
	"fmt"

	"github.com/jessevdk/go-flags"

	"github.com/snapcore/snapd/i18n"
	"github.com/snapcore/snapd/systemd/logind"
)

type cmdRoutineUserServicePrecondition struct {
	clientMixin
	ErrorExitCode int `long:"error-exit-code" default:"1"`
}

var shortRoutineUserServicePreconditionHelp = i18n.G("Check whether user services should run in this session")
var longRoutineUserServicePreconditionHelp = i18n.G(`
The user-service-precondition command exits 0 if invoked from a session in
which user services should run. It exits non-zero (1 by default, or the
value of --error-exit-code) if the session is a greeter session, or if the
session class cannot be determined.

This command is intended for use as an ExecCondition stanza in systemd user
service files generated by snapd.
`)

var logindSessionClass = logind.SessionClass

func init() {
	c := addRoutineCommand("user-service-precondition", shortRoutineUserServicePreconditionHelp, longRoutineUserServicePreconditionHelp, func() flags.Commander {
		return &cmdRoutineUserServicePrecondition{}
	}, map[string]string{
		// TRANSLATORS: This should not start with a lowercase letter.
		"error-exit-code": i18n.G("Exit code to use when the session is a greeter session or no session is found"),
	}, nil)
	c.hidden = true
}

func (x *cmdRoutineUserServicePrecondition) Execute(args []string) error {
	if len(args) > 0 {
		return ErrExtraArgs
	}
	if x.ErrorExitCode < 1 || x.ErrorExitCode > 255 {
		fmt.Fprintf(Stderr, "invalid --error-exit-code: must be in range 1-255")
		panic(&exitStatus{code: 1}) // best we can do
	}

	class, err := logindSessionClass(context.Background())
	if err != nil {
		fmt.Fprintf(Stderr, "cannot determine session class: %v\n", err)
		panic(&exitStatus{code: x.ErrorExitCode})
	}

	if class == "greeter" {
		panic(&exitStatus{code: x.ErrorExitCode})
	}

	return nil
}
