#!/bin/sh

CONTROL_FILE="$SNAP_COMMON"/control

snapctl refresh --pending > "$SNAP_COMMON"/debug.log

if [ -f "$CONTROL_FILE" ]; then
    COMMAND=$(cat "$CONTROL_FILE")
    snapctl refresh "$COMMAND" > "$SNAP_COMMON"/debug.log 2>&1
fi
