#!/bin/sh -xe

# save the original value so we can check it in the test
value=$(snapctl get --view :network-ephemeral-wifi-admin password)
echo "$value" >> "$SNAP_COMMON"/change-view-network-ephemeral-wifi-admin-ran

# check we can modify it
snapctl set --view :network-ephemeral-wifi-admin password="$value-changed"
