#!/bin/sh -xe

# save the previous value for test validation
value=$(snapctl get --view :network-ephemeral-wifi-admin password)
echo "$value" >> "$SNAP_COMMON"/query-view-network-ephemeral-wifi-admin-ran

# add a suffix so we can check query-view can modify values
snapctl set --view :network-ephemeral-wifi-admin password="$value-queried"
