#!/bin/sh

# Copyright (C) 2015 Canonical Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This runs the $1 go test binary and reboots if necessary.

set -e

TEST=$1
NEEDS_REBOOT=/tmp/needs-reboot

./${TEST} -check.vv -test.outputdir=$ADT_ARTIFACTS-$ADT_REBOOT_MARK

if [ -e ${NEEDS_REBOOT} ]; then
    mark=`cat ${NEEDS_REBOOT}`
    echo "Rebooting..."
    sudo /tmp/autopkgtest-reboot "$mark"
fi
