name: Build arch package

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'A json list of tags to indicate which runner to use'
        required: true
        type: string

jobs:
  build-arch:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download vendor
      uses: actions/download-artifact@v4
      with:
        name: vendor-pkgs
        path: /tmp/pkg

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image with cache support
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        file: tests/lib/packaging/arch.dockerfile
        tags: arch-base:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set version in spec
      run: |
        version=$(cat /tmp/pkg/version)
        sed -i -e "s/pkgver=.*/pkgver=$version/" packaging/arch/PKGBUILD

    - name: Build arch pkg
      run: |
        chmod -R a+w .
        docker run --cap-add SYS_ADMIN --rm \
          --mount type=bind,src=$(pwd),dst=/home/test/snapd \
          --mount type=bind,src=/tmp/pkg,dst=/tmp/pkg \
          arch-base:latest \
          bash -c "
            cd /home/test/snapd && \
            tests/lib/packaging/build-arch.sh --user test --build-dir /tmp/pkg/
          "
        mkdir /tmp/uploads
        sudo find /tmp/pkg/* -name '*.pkg.tar.*' -exec mv {} /tmp/uploads \;

    - name: upload packages
      uses: actions/upload-artifact@v4
      with:
        name: package-arch-linux-64
        path: /tmp/uploads
