# SPDX-FileCopyrightText: 2026 Canonical Ltd
# SPDX-License-Identifier: GPL-3.0-only

name: Prepare the REST OpenAPI Specification
on:
  pull_request:

jobs:
  check-api:
    runs-on: ubuntu-latest
    name: Check REST API documentation changes
    outputs:
      api_changed: ${{ steps.changed-api.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check if changes occurred in the API documentation
        id: changed-api
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          files: docs/api/**

  process-specification:
    needs: check-api
    if: needs.check-api.outputs.api_changed == 'true'
    runs-on: ubuntu-latest
    name: Bundle REST API documentation
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check Licensing/Copyright Compliance
        uses: docker://fsfe/reuse
        with:
          entrypoint: /bin/sh
          args: -c "cd docs/api && reuse lint"

      - name: Lint API specification
        uses: docker://redocly/cli
        with:
          args: lint ./docs/api/openapi.yaml

      - name: Bundle OpenAPI to JSON
        uses: docker://redocly/cli
        with:
          args: bundle ./docs/api/openapi.yaml --output ./docs/api/openapi.json --ext json

      - name: Store generated JSON artifact
        uses: actions/upload-artifact@v6
        with:
          name: openapi-spec
          path: docs/api/openapi.json
