name: Tests
on:
  pull_request:
    branches: [ "master", "release/**", "core-snap-security-release/**", "security-release/**", "hotfix/**" ]
  push:
    branches: [ "release/**", "core-snap-security-release/**", "security-release/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  go-channels:
    runs-on: ubuntu-latest
    outputs:
      go-channels: ${{ steps.resolve-go-channels.outputs.go-channels }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Resolve Go snap channels
        id: resolve-go-channels
        uses: ./.github/actions/resolve-go-channels
        with:
          include-snapd-build-go-channel: true
          include-snapd-build-fips-go-channel: true
          include-latest-go-channel: false

  snap-builds:
    uses: ./.github/workflows/snap-builds.yaml
    with:
      runs-on: ${{ matrix.runs-on }}
      toolchain: ${{ matrix.toolchain }}
      variant: ${{ matrix.variant }}
    strategy:
      matrix:
        runs-on:
          - '["ubuntu-22.04"]'
          - ${{ github.event.repository.private && '["self-hosted", "Linux", "jammy", "ARM64", "large"]' || '["ubuntu-22.04-arm"]' }}
        toolchain:
          - default
          - FIPS
        variant:
          # test version is a build of snapd with test keys and should
          # only be installed by test runners. The pristine versions
          # are the build that should be installed by human users.
          - pristine
          - test
        # Exclude building everything for ARM but the version for testing
        # to keep the number of builds down as we currently don't have a
        # clear need for these excluded builds.
        exclude:
          - runs-on: ${{ github.event.repository.private && '["self-hosted", "Linux", "jammy", "ARM64", "large"]' || '["ubuntu-22.04-arm"]' }}
            toolchain: FIPS
          - runs-on: ${{ github.event.repository.private && '["self-hosted", "Linux", "jammy", "ARM64", "large"]' || '["ubuntu-22.04-arm"]' }}
            variant: pristine

  create-vendor-dir:
    runs-on: ubuntu-latest
    name: Create go vendor
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: vendor
        run: |
          sudo snap install --classic --channel 1.18/stable go
          /snap/bin/go mod vendor
          (
            cd c-vendor
            ./vendor.sh
          )
          mkdir /tmp/pkg
          base_version="$(head -1 packaging/ubuntu-16.04/changelog | awk -F '[()]' '{print $2}')"
          version="1337.$base_version"
          ./packaging/pack-source -v "$version" -o /tmp/pkg
          ./packaging/pack-source -v "$version" -o /tmp/pkg -s
          echo "$version" > /tmp/pkg/version

      - name: Upload vendors
        uses: actions/upload-artifact@v7
        with:
          name: vendor-pkgs
          path: /tmp/pkg

  package-snapd-rpm-mock:
    needs: create-vendor-dir
    uses: ./.github/workflows/rpm-mock-builds.yaml
    name: Package ${{ matrix.build-config.system }}
    with:
      runs-on: '["ubuntu-latest"]'
      system: ${{ matrix.build-config.system }}
      pkg-dir: ${{ matrix.build-config.pkg-dir }}
      config: ${{ matrix.build-config.config }}
    strategy:
      fail-fast: false
      matrix:
        build-config:
          - { system: fedora-42-64,           pkg-dir: fedora-42,            config: fedora-42-x86_64           }
          - { system: centos-9-64,            pkg-dir: centos-9,             config: centos-stream-9-x86_64     }

  package-snapd-rpm-rpmbuild:
    needs: create-vendor-dir
    uses: ./.github/workflows/rpm-rpmbuild-builds.yaml
    secrets: inherit
    name: Package ${{ matrix.build-config.system }}
    with:
      runs-on: '["ubuntu-latest"]'
      pkg-dir: ${{ matrix.build-config.pkg-dir }}
      system: ${{ matrix.build-config.system }}
      dockerfile: ${{ matrix.build-config.dockerfile }}
      image-name: ${{ matrix.build-config.image-name }}
      image-tag: ${{ matrix.build-config.image-tag }}
    strategy:
      fail-fast: false
      matrix:
        build-config:
          - { system: "opensuse-tumbleweed-64", dockerfile: "opensuse.dockerfile", image-name: "opensuse/tumbleweed", image-tag: "latest", pkg-dir: "opensuse-tumbleweed" }
          - { system: "opensuse-15.6-64",       dockerfile: "opensuse.dockerfile", image-name: "opensuse/leap",       image-tag: "15.6",   pkg-dir: "opensuse-15.6"       }
          - { system: "opensuse-16.0-64",       dockerfile: "opensuse.dockerfile", image-name: "opensuse/leap",       image-tag: "16.0",   pkg-dir: "opensuse-16.0"       }
          - { system: "amazon-linux-2-64",      dockerfile: "amazon.dockerfile",   image-name: "amazonlinux",         image-tag: "2",      pkg-dir: "amzn-2"              }
          - { system: "amazon-linux-2023-64",   dockerfile: "amazon.dockerfile",   image-name: "amazonlinux",         image-tag: "2023",   pkg-dir: "amzn-2023"           }

  package-snapd-arch:
    needs: create-vendor-dir
    uses: ./.github/workflows/arch-builds.yaml
    name: Package arch-linux-64
    with:
      runs-on: '["ubuntu-latest"]'

  package-snapd-deb:
    needs: create-vendor-dir
    uses: ./.github/workflows/deb-builds.yaml
    name: Package ${{ matrix.build-config.system }}
    with:
      runs-on: ${{ matrix.build-config.runs-on }}
      system: ${{ matrix.build-config.system }}
      os-version: ${{ matrix.build-config.os-version }}
      os: ${{ matrix.build-config.os }}
    strategy:
      fail-fast: false
      matrix:
        build-config:
          - { system: "ubuntu-26.04-64",     runs-on: '["ubuntu-latest"]',     os: ubuntu, os-version: '26.04' }
          - { system: "ubuntu-25.10-64",     runs-on: '["ubuntu-latest"]',     os: ubuntu, os-version: '25.10' }
          - { system: "ubuntu-25.04-64",     runs-on: '["ubuntu-latest"]',     os: ubuntu, os-version: '25.04' }
          - { system: "ubuntu-24.04-64",     runs-on: '["ubuntu-latest"]',     os: ubuntu, os-version: '24.04' }
          - { system: "ubuntu-22.04-64",     runs-on: '["ubuntu-latest"]',     os: ubuntu, os-version: '22.04' }
          - { system: "ubuntu-20.04-64",     runs-on: '["ubuntu-latest"]',     os: ubuntu, os-version: '20.04' }
          - { system: "ubuntu-18.04-64",     runs-on: '["ubuntu-latest"]',     os: ubuntu, os-version: '18.04' }
          - { system: "debian-sid-64",       runs-on: '["ubuntu-latest"]',     os: debian, os-version: 'sid'   }
          - { system: "ubuntu-24.04-arm-64", runs-on: '["ubuntu-24.04-arm"]',  os: ubuntu, os-version: '24.04' }
          - { system: "ubuntu-22.04-arm-64", runs-on: '["ubuntu-24.04-arm"]',  os: ubuntu, os-version: '22.04' }

  cache-build-deps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Download Debian dependencies
      run: |
          sudo apt clean
          sudo apt update
          ln -s packaging/ubuntu-16.04 debian
          sudo apt build-dep -d -y ${{ github.workspace }}
          # for indent
          sudo apt install texinfo autopoint

    - name: Copy dependencies
      run: |
        sudo tar cvf cached-apt.tar /var/cache/apt

    - name: upload Debian dependencies
      uses: actions/upload-artifact@v7
      with:
        name: debian-dependencies
        path: ./cached-apt.tar

 
  read-systems:
    runs-on: ubuntu-latest
    # This dependency only serves to ensure this job runs after the
    # labeler finishes its work
    needs: snap-builds
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      fundamental-systems: ${{ steps.read-systems.outputs.fundamental-systems }}
      non-fundamental-systems: ${{ steps.read-systems.outputs.non-fundamental-systems }}
      nested-systems: ${{ steps.read-systems.outputs.nested-systems }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Read matrix file
        id: read-systems
        shell: bash
        run: |
          set -x
          echo "fundamental-systems=$(jq -c . ./.github/workflows/data-fundamental-systems.json)" >> $GITHUB_OUTPUT
          echo "non-fundamental-systems=$(jq -c . ./.github/workflows/data-non-fundamental-systems.json)" >> $GITHUB_OUTPUT
          echo "nested-systems=$(jq -c . ./.github/workflows/data-nested-systems.json)" >> $GITHUB_OUTPUT

          if [ -n "${{ github.event.pull_request.number }}" ]; then
            labels=$(gh pr view ${{ github.event.pull_request.number }} --json labels | jq -r '.labels[].name')
            if grep -q '^Run only one system$' <<<$labels; then
              body="$(gh pr view ${{ github.event.pull_request.number }} --json body --jq .body)"

              # grab the regex that follows the #runonlyonesystem tag if it exists
              # if it doesn't exist, don't fail here; that case will be caught when checking
              # the number of filtered systems vs. total systems
              filter="$(grep -ioP '#runonlyonesystem\K.*' <<<"$body" || true)"
              # remove all whitespaces (systems shouldn't have spaces in their names anyway)
              filter="$(tr -d '[:space:]' <<<"$filter")"

              # use the regex to filter in systems in both fundamental and non-fundamental systems
              fundamental_systems="$(jq -c --arg regex "$filter" '.include |= map(select(.systems | test($regex)))' .github/workflows/data-fundamental-systems.json)"
              non_fundamental_systems="$(jq -c --arg regex "$filter" '.include |= map(select(.systems | test($regex)))' .github/workflows/data-non-fundamental-systems.json)"

              # count the number of systems selected vs. total number
              selected_fund="$(grep -o "systems" <<<"$fundamental_systems" | wc -l || true)"
              selected_non_fund="$(grep -o "systems" <<<"$non_fundamental_systems" | wc -l || true)"
              total_fund="$(jq -c . .github/workflows/data-fundamental-systems.json | grep -o "systems" | wc -l)"
              total_nonfund="$(jq -c . .github/workflows/data-non-fundamental-systems.json | grep -o "systems" | wc -l)"

              # if no systems were filtered in, then filter in only noble
              # this condition can trigger if something like a '.*' was used as regex or
              # if the #runonlyonesystem tag was not present in the PR description
              if [[ ( "$selected_fund" -eq "$total_fund" && "$selected_non_fund" -eq "$total_nonfund" ) || \
                 ( "$selected_fund" -eq 0 && "$selected_non_fund" -eq 0 ) ]]; then
                echo "filtering out everything except for noble since no systems were filtered out"
                echo "If you wanted to choose different systems to run, use the #runonlyonesystem tag followed by a regex of what you wish to select"
                echo "filtered fundamental systems are $fundamental_systems"
                echo "filtered non-fundamental systems are $non_fundamental_systems"
                fundamental_systems="$(jq -c --arg regex 'ubuntu-24.04-64' '.include |= map(select(.systems | test($regex)))' .github/workflows/data-fundamental-systems.json)"
                non_fundamental_systems="$(jq -c --arg regex 'ubuntu-24.04-64' '.include |= map(select(.systems | test($regex)))' .github/workflows/data-non-fundamental-systems.json)"
              fi

              echo "fundamental-systems=$fundamental_systems" >> $GITHUB_OUTPUT
              echo "non-fundamental-systems=$non_fundamental_systems" >> $GITHUB_OUTPUT

              if ! grep -q '^Run nested$' <<<$labels; then
                echo "nested-systems=" >> $GITHUB_OUTPUT
              fi
            fi
          fi

  spread-fundamental:
    uses: ./.github/workflows/spread-tests.yaml
    needs: [snap-builds, read-systems]
    if: contains(needs.read-systems.outputs.fundamental-systems, 'systems')
    name: "spread ${{ matrix.group }}"
    secrets: inherit
    with:
      # Github doesn't support passing sequences as parameters.
      # Instead here we create a json array and pass it as a string.
      # Then in the spread workflow it turns it into a sequence 
      # using the fromJSON expression.
      runs-on: '${{ matrix.runs-on }}'
      group: ${{ matrix.group }}
      backend: ${{ matrix.backend }}
      alternative-backend: ${{ matrix.alternative-backend }}
      systems: ${{ matrix.systems }}
      tasks: ${{ matrix.tasks }}
      rules: ${{ matrix.rules }}
      is-fundamental: true
    strategy:
      # FIXME: enable fail-fast mode once spread can cancel an executing job.
      # Disable fail-fast mode as it doesn't function with spread. It seems
      # that cancelling tasks requires short, interruptible actions and
      # interrupting spread, notably, does not work today. As such disable
      # fail-fast while we tackle that problem upstream.
      fail-fast: false
      matrix: ${{ fromJson(needs.read-systems.outputs.fundamental-systems) }}

  # The spread-results-reporter needs the PR number to be able to 
  # comment on the relevant PR with spread failures. Because the PR 
  # number is not in the github.event object during the 
  # spread-results-reporter.yaml job run, we upload it along side other 
  # artifacts to be subsequently downloaded by spread-results-reporter.
  upload_pr_number:
    if: ${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Create PR number file
        run: echo "${{ github.event.pull_request.number }}" > pr_number
      
      - name: Upload PR number
        uses: actions/upload-artifact@v7
        with:
          name: pr_number 
          path: pr_number
