name: Build deb package

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'A json list of tags to indicate which runner to use'
        required: true
        type: string
      os:
        description: 'The OS to build the deb package for'
        required: true
        type: string
      os-version:
        description: 'The OS version to build the deb package for'
        required: true
        type: string
      system:
        description: 'The system name as known by spread'
        required: true
        type: string

jobs:
  build-deb:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Download source tarballs
      uses: actions/download-artifact@v8
      with:
        name: source-tarball
        path: /tmp/source

    - name: Extract source tarballs
      run: |
        # Extract version from tarball filename
        version=$(ls /tmp/source/snapd_*.no-vendor.tar.xz | sed -E 's/.*snapd_(.*)\.no-vendor.*/\1/')
        echo "PKG_VERSION=$version" >> $GITHUB_ENV

        # Extract source tarballs
        mkdir -p /tmp/source-extracted
        cd /tmp/source-extracted
        tar -xf /tmp/source/snapd_*.no-vendor.tar.xz
        tar -xf /tmp/source/snapd_*.only-vendor.tar.xz

        # Move extracted content to current directory
        cd -
        mv /tmp/source-extracted/snapd-*/vendor .
        mv /tmp/source-extracted/snapd-*/c-vendor/* c-vendor/

    - name: Setup debian dir
      run: |
        # top level debian directory must not exist
        test ! -d debian
        target_system="${{ inputs.os }}-${{ inputs.os-version }}"
        case "$target_system" in
            debian-sid)
                ln -sfn packaging/debian-sid debian
                ;;
            ubuntu-*)
                ln -sfn packaging/ubuntu-16.04 debian
                ;;
            *)
                echo "unsupported deb packaging for $target_system"
                exit 1
                ;;
        esac

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Build Docker image
      uses: docker/build-push-action@v7
      with:
        context: .
        push: false
        load: true
        file: tests/lib/packaging/debian.dockerfile
        build-args: |
          SYSTEM=${{ inputs.os }}
          TAG=${{ inputs.os-version }}
        tags: deb-base:latest

    - name: Build deb
      run: |
        chmod a+w ../
        chmod -R a+w .
        mkdir -p /tmp/builds
        chmod -R a+w /tmp/builds
        docker run --cap-add SYS_ADMIN --rm \
          --mount type=bind,src=$(dirname $(pwd)),dst=/home/test/snapd-parent \
          --mount type=bind,src=/tmp/builds,dst=/tmp/builds \
          deb-base:latest \
          bash -c "
            chown -R test:test /home/test/snapd-parent/snapd* && \
            cd /home/test/snapd-parent/snapd* && \
            tests/lib/packaging/build-deb.sh --user test --pkg-version ${{ env.PKG_VERSION }} && \
            cp /home/test/snapd-parent/*.deb /tmp/builds
          "

    - name: upload packages
      uses: actions/upload-artifact@v7
      with:
        name: package-${{ inputs.system }}
        path: /tmp/builds/
