name: Go
on: [push]
jobs:
  static:
    name: Quick
    runs-on: ubuntu-16.04
    steps:
    - name: Set up Go 1.9
      uses: actions/setup-go@v1
      with:
        go-version: 1.9
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run checks
      run: |
        ./run-checks --static
        ./run-checks --short-unit

