name: Nightly spread coverage

on:
  pull_request:
    branches: [ "master" ]

jobs:
  snap-builds:
    uses: ./.github/workflows/snap-builds.yaml
    with:
      runs-on: '["ubuntu-22.04"]'
      toolchain: default
      variant: test

  read-systems:
    runs-on: ubuntu-latest
    outputs:
      systems: ${{ steps.read-systems.outputs.systems }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Read matrix file
        id: read-systems
        shell: bash
        run: |
          echo "systems=$(jq -cs '{include: (map(.include // []) | add)}' \
            ./.github/workflows/data-fundamental-systems.json \
            ./.github/workflows/data-non-fundamental-systems.json \
            ./.github/workflows/data-nested-systems.json)" >> $GITHUB_OUTPUT

  spread-coverage:
    uses: ./.github/workflows/spread-tests.yaml
    name: "spread master ${{ matrix.group }}"
    needs: [read-systems, snap-builds]
    secrets: inherit
    with:
      runs-on: '${{ matrix.runs-on }}'
      group: ${{ matrix.group }}
      backend: ${{ matrix.backend }}
      alternative-backend: ${{ matrix.alternative-backend }}
      systems: ${{ matrix.systems }}
      tasks: ${{ matrix.tasks }}
      rules: ${{ matrix.rules }}
      upload-artifacts: true
      spread-env: "SPREAD_GENERATE_COVERAGE=true"
      skip-tests: 'ubuntu-14.04-64 tests/lib/ tests/unit/ tests/utils/cross-build ubuntu-fips-2'
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.read-systems.outputs.systems) }}

  process-coverage:
    runs-on: ubuntu-latest
    if: always()
    needs: [spread-coverage]
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v8
        with:
          path: coverage
          pattern: spread-artifacts-*
          merge-multiple: true

      - name: Download spread results artifacts
        uses: actions/download-artifact@v8
        with:
          path: coverage
          pattern: spread-results-*

      - name: tree
        run: |
          sudo apt install tree
          tree coverage
