name: Nightly spread coverage

on:
  pull_request:
    branches: [ "master" ]

jobs:
  snap-builds:
    uses: ./.github/workflows/snap-builds.yaml
    with:
      runs-on: '["ubuntu-22.04"]'
      toolchain: default
      variant: test

  # nightly-spread-coverage:
  #   uses: ./.github/workflows/spread-tests.yaml
  #   needs: snap-builds
  #   name: "spread"
  #   secrets: inherit
  #   with:
  #     runs-on: '["self-hosted", "spread-enabled"]'
  #     group: noble
  #     backend: openstack
  #     systems: ubuntu-24.04-64
  #     tasks: tests/...
  #     rules: main
  #     upload-artifacts: true
  #     spread-env: "SPREAD_GENERATE_COVERAGE=true"

  nightly-spread-coveragea:
    uses: ./.github/workflows/spread-tests.yaml
    needs: snap-builds
    name: "spread fedora"
    secrets: inherit
    with:
      runs-on: '["self-hosted", "spread-enabled"]'
      group: fedora
      backend: openstack
      systems: fedora-44-64
      tasks: tests/...
      rules: main
      upload-artifacts: true
      spread-env: "SPREAD_GENERATE_COVERAGE=true"

  nightly-spread-coverageb:
    uses: ./.github/workflows/spread-tests.yaml
    needs: snap-builds
    name: "spread fedora"
    secrets: inherit
    with:
      runs-on: '["self-hosted", "spread-enabled"]'
      group: arch
      backend: openstack
      systems: arch-linux-64
      tasks: tests/...
      rules: main
      upload-artifacts: true
      spread-env: "SPREAD_GENERATE_COVERAGE=true"

  nightly-spread-coveragec:
    uses: ./.github/workflows/spread-tests.yaml
    needs: snap-builds
    name: "spread 18"
    secrets: inherit
    with:
      runs-on: '["self-hosted", "spread-enabled"]'
      group: ubuntu-18
      backend: openstack
      systems: ubuntu-18.04-64
      tasks: tests/...
      rules: main
      upload-artifacts: true
      spread-env: "SPREAD_GENERATE_COVERAGE=true"

  # nightly-spread-coverage-nested:
  #   uses: ./.github/workflows/spread-tests.yaml
  #   needs: snap-builds
  #   name: "spread nested"
  #   secrets: inherit
  #   with:
  #     runs-on: '["self-hosted", "spread-enabled"]'
  #     group: nested
  #     backend: openstack-ext
  #     systems: ubuntu-24.04-64
  #     tasks: tests/nested/classic/...
  #     rules: nested
  #     upload-artifacts: true
  #     spread-env: "SPREAD_GENERATE_COVERAGE=true"

  # process-coverage:
  #   runs-on: ubuntu-latest
  #   needs: [nightly-spread-coverage]
  #   steps:
  #     - name: Download coverage artifacts
  #       uses: actions/download-artifact@v8
  #       with:
  #         path: coverage
  #         pattern: spread-artifacts-*
  #         merge-multiple: true

  #     - name: Download spread results artifacts
  #       uses: actions/download-artifact@v8
  #       with:
  #         path: coverage
  #         pattern: spread-results-*

  #     - name: tree
  #       run: |
  #         sudo apt install tree
  #         tree coverage
