name: Build rpm package

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'A json list of tags to indicate which runner to use'
        required: true
        type: string
      system:
        description: 'The system, as known to spread, to build the rpm package for'
        required: true
        type: string
      pkg-dir:
        description: 'The name of the relevant folder in packaging directory'
        required: true
        type: string
      config:
        description: 'The name of the mock config file'
        required: true
        type: string

jobs:
  build-rpm:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download vendor
      uses: actions/download-artifact@v4
      with:
        name: vendor-pkgs
        path: /tmp/pkg

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image with cache support
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        file: tests/lib/packaging/fedora.dockerfile
        tags: mock-base:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Create cache key
      # Force a cache refresh once a week by using the year and week number as part of the cache key
      run: echo "CACHE_KEY=mock-cache-${{ inputs.system }}-$(date '+%Y-%U')" >> $GITHUB_ENV

    - name: Cache mock dependencies
      uses: actions/cache@v4
      with:
        path: /tmp/mock
        key: ${{ env.CACHE_KEY }}

    - name: Run mock inside container
      run: |
        chmod -R 777 .
        mkdir -p /tmp/mock
        mkdir -p /tmp/builds
        chmod -R 777 /tmp/builds
        docker run --privileged --rm \
          --mount type=bind,src=/tmp/mock,dst=/var/cache/mock \
          --mount type=bind,src=$(pwd),dst=/home/mockbuilder/snapd \
          --mount type=bind,src=/tmp/pkg,dst=/tmp/pkg \
          --mount type=bind,src=/tmp/builds,dst=/home/mockbuilder/builds \
          mock-base:latest \
          bash -c "
            mock -r /etc/mock/${{ inputs.config }}.cfg --install git && \
            cd /home/mockbuilder/snapd && \
            tests/lib/packaging/build-source-rpm.sh ${{ inputs.pkg-dir }} /tmp/pkg && \
            mock -r /etc/mock/${{ inputs.config }}.cfg --no-clean --no-cleanup-after --enable-network --nocheck --with testkeys --resultdir /home/mockbuilder/builds /home/mockbuilder/rpmbuild/SRPMS/snapd-*.src.rpm
          "
        mkdir /tmp/uploads
        sudo find /tmp/builds/* -type f \
          ! -name '*debug*' \
          ! -name '*.src.rpm' \
          -name '*.rpm' \
          -exec mv {} /tmp/uploads \;

    - name: upload packages
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ inputs.system }}
        path: /tmp/uploads
