name: Build snaps

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'A json list of tags to indicate which runner to use'
        required: true
        type: string
      toolchain:
        description: 'The go toolchain to use {default, FIPS}'
        required: true
        type: string
      variant:
        description: 'The type of snapd build {pristine, test}'
        required: true
        type: string

jobs:
  snap-builds:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    
    - name: Build and upload snap
      uses: ./.github/actions/build-snap-checks
      with:
        toolchain: ${{ inputs.toolchain }}
        variant: ${{ inputs.variant }}
        runs-on: ${{ inputs.runs-on }}
        pr-number: ${{ github.event.pull_request.number || '' }}

    
