name: Snap Build
on:
  pull_request:
    branches: ["master", "release/**"]
jobs:
  build:
    name: Build the snapd snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the snapd snap
        uses: snapcore/action-build@v1
      - name: Uploading snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap-files
          path: "*.snap"
