name: Spread tests results PR commenter

on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

jobs:
  report-spread-failures:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
      TEST_PREDICTOR_URL: http://test-predictor.snapd.canonical.com:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get PR number
        uses: actions/github-script@v9
        with:
          script: |
            let page = 1;
            let per_page = 100;
            let allArtifacts = [];
            let response;
            do {
              response = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id,
                per_page: per_page,
                page: page
              });
              allArtifacts = allArtifacts.concat(response.data.artifacts);
              page++;
            } while (allArtifacts.length < response.data.total_count);
            let matchArtifact = allArtifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));
           
      - name: Unzip PR number
        run: unzip pr_number.zip

      - name: Get generated data
        uses: actions/github-script@v9
        with:
          script: |
            let page = 1;
            let per_page = 100;
            let allArtifacts = [];
            let response;
            do {
              response = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id,
                per_page: per_page,
                page: page
              });
              allArtifacts = allArtifacts.concat(response.data.artifacts);
              page++;
            } while (allArtifacts.length < response.data.total_count);

            let matchingArtifacts = allArtifacts.filter((artifact) => {
              return artifact.name.startsWith(`spread-results-${context.payload.workflow_run.id}-${context.payload.workflow_run.run_attempt}`);
            });

            for (let artifact of matchingArtifacts) {
              let download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
                archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${artifact.name}.zip`, Buffer.from(download.data));
              console.log(`Downloaded artifact: ${artifact.name}.zip`);
            }

            let matchingSkips = allArtifacts.filter((artifact) => {
              return artifact.name.startsWith(`skipped-tests-list-${context.payload.workflow_run.id}`);
            });

            for (let artifact of matchingSkips) {
              let download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
                archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${artifact.name}.zip`, Buffer.from(download.data));
              console.log(`Downloaded artifact: ${artifact.name}.zip`);
            }
 
      - name: Unzip spread json files
        run: |
          find . -name "spread-results-${{ github.event.workflow_run.id }}*.zip" | while read filename; do 
            dir="${filename%.zip}"
            mkdir "$dir"
            unzip "$filename" -d "$dir"
          done
 
      - name: Unzip spread skip files
        run: |
          find . -name "skipped-tests-list-${{ github.event.workflow_run.id }}*.zip" | while read filename; do 
            dir="${filename%.zip}"
            mkdir "$dir"
            unzip "$filename" -d "$dir"
          done

      - name: Echo collected output
        run: |
          bash .github/scripts/test-predictor-reporter.sh \
            "${{ github.repository }}" \
            "${{ github.event.workflow_run.id }}" \
            "${{ github.event.workflow_run.run_attempt }}"

      - name: Comment report to PR
        run: |
          if ! gh pr comment "$(cat pr_number)" --body "$(cat report)" --edit-last; then
            gh pr comment "$(cat pr_number)" --body "$(cat report)"
          fi
